- src/components/Tree/src/BasicTree.tsx
> ℹ️ Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](https://github.com/vuejs/awesome-vue/blob/master/.github/contributing.md).
> fix: 修复树组件点击选中

- src/components/Preview/src/index.less
> Style(Preview): Modify the button to center vertically

- README.en-US.md
- README.md
> feat: add README.en-US.md

- src/components/StrengthMeter/index.less
- src/components/StrengthMeter/index.tsx
> perf(strength-meter): modify name word

- README.en-US.md
- README.md
> fix: 修复跳转链接

- src/components/Container/src/collapse/CollapseContainer.vue
> 修复插槽多级传递问题

- src/components/Form/src/BasicForm.vue
- src/components/Form/src/props.ts
- src/components/Form/src/types/form.ts
> perf: 为form添加顶层row的style注入。

- src/components/Table/src/components/renderEditable.tsx
> fix(table): fix unsuccessful saving of row edit table

- src/components/Menu/src/BasicMenu.tsx
> 左侧菜单栏 超出高度滚动失效

- src/setup/theme/index.ts
Add css filters to `html` instead of `body`
> fix(theme): css filter breaking fixed position

- src/router/index.ts
> fix(router): reserving `Redirect` after reset

- src/enums/pageEnum.ts
> fix: invalid error-log page path

- src/components/Table/src/components/editable/EditableCell.vue
> 修正可编辑单元格初始数据显示

- src/components/Form/src/hooks/useFormValues.ts
> fix(form): format 解构赋值错误

- src/components/Container/src/collapse/CollapseHeader.vue
> fix: fix collapse header title not rendering

- src/components/Description/src/index.tsx
> fix(description): not rendering while show method return false

- src/views/dashboard/workbench/components/ShortCuts.vue
查看 demo 发现 dashboard 模块的 workbench 页面快捷入口样式异常，已修复。
由于图片底部 margin `mb-2` class 被覆盖，所以不使用 `margin: 0 auto;`, 使用 `margin-left: auto; margin-right: auto;` 修复。
本机环境：M1 Macbook Pro，Chrome 88.0.4324.150, Safari 14.0.3 (16610.4.3.1.4)
> fix(dashboard): fix workbench page style

- src/components/Page/src/PageFooter.vue
> fix: change transition-duration to make animate smoothly

- src/router/guard/progressGuard.ts
progress有时会不能完成，例如不断重复几次登出和登录，就会出现这个问题。done觉得还是一定执行比较好。
> fix(progress): fix progress sometimes cannot done

- mock/sys/menu.ts
> fix: welcome page not cached in back-end mode

- src/components/Modal/src/BasicModal.vue
> fix(modal):Modifying the loadingTip property does not work

- src/router/helper/routeHelper.ts
> LayoutMap 无法正确get的bug

- src/views/sys/login/Login.vue
> fix: login page overflow show problem

- src/components/Cropper/src/index.vue
- src/components/Verify/src/ImgRotate.tsx
- src/views/demo/comp/cropper/index.vue
> fix: Improve the picture cropping component

- src/components/Form/src/hooks/useFormEvents.ts
- src/components/Form/src/hooks/useFormValues.ts
> 在 BasicForm 中自定义组件时未抛出验证错误，自定义组件 Array 的元素可能为null

- src/views/demo/comp/cropper/index.vue
> perf: improve cropper example

- src/components/CountTo/src/index.vue
- src/components/CountTo/src/props.ts
- src/views/demo/comp/count-to/index.vue
> perf: improve countTo

- src/views/sys/login/Login.vue
> fix: password icon dislocation

- src/views/demo/form/AppendForm.vue
> 修复AppendFormDemo

- src/views/demo/form/index.vue
> perf: add Coordinating the selection of provinces and cities

- src/components/Form/src/componentMap.ts
- src/components/Form/src/types/index.ts
- src/views/demo/form/index.vue
> ℹ️ What types of changes does your code isntroduce?
> feat(function): add 增加Slider滑动输入条组件及demo

- src/utils/http/axios/Axios.ts
> set header can use For Qs

- src/components/Table/src/hooks/useCustomRow.ts
- src/components/Tree/src/index.vue
> 解决两个Issues：#548,#557

- src/components/Tree/src/index.vue
> fix(tree): basicTree设置blockNode=false后，显示异常

- src/components/Table/src/hooks/useColumns.ts
> fix(table): columns ref fixed(#564)

- src/components/Form/src/hooks/useFormValues.ts
> feat(form): add form field nested support

- src/utils/cipher.ts
> fix(cipher): fix #587

- src/store/modules/multipleTab.ts
> fix(store): addTab updateCacheTab

- build/config/themeConfig.ts
> fix(theme generate): Fix #604

- src/components/Table/src/BasicTable.vue
> style: fix the background color of table striped is lose

- src/components/Form/src/BasicForm.vue
- src/components/Form/src/props.ts
- src/components/Form/src/types/form.ts
为Form添加autoSubmitOnEnter属性，当设置为true时，可以在input组件上按下回车时自动提交表单
> feat(form): add prop autoSubmitOnEnter

- src/components/Form/src/components/FormItem.vue
修复为RangePicker组件设置的placeholder属性无效的BUG。
> fix(form): placeholder setting in componentProps

- mock/demo/table-demo.ts
- src/components/Table/src/componentMap.ts
- src/components/Table/src/components/editable/helper.ts
- src/components/Table/src/types/componentType.ts
- src/views/demo/table/EditCellTable.vue
- src/views/demo/table/EditRowTable.vue
> feat(table): add editable DatePicker & TimePicker

- src/locales/lang/en/sys.ts
- src/locales/lang/zh_CN/sys.ts
- src/store/modules/user.ts
- src/utils/http/axios/Axios.ts
- src/utils/http/axios/index.ts
- src/views/sys/login/LoginForm.vue
- 修改axios的transformRequestHook工作方式，使得页面可以捕获具体的错误信息。
- 基于上一条，修复LOGIN页面在token过期时因为层级问题无法正确显示错误提示的问题。
> fix(login): login page modal style fixed: #662

- src/hooks/web/useTabs.ts
- src/store/modules/multipleTab.ts
- src/views/demo/feat/tabs/index.vue
> feat(tabs): add setTabTitle method

- src/components/CodeEditor/src/codemirror/CodeMirror.vue
> fix(codeMirror):  修复json编辑器在弹框内嵌导致样式错乱的bug

- src/components/Tinymce/src/Editor.vue
feat(Tinymce): 为富文本编辑器只读状态添加动态性
> feat(Tinymce):  为富文本编辑器只读状态添加动态性

- src/layouts/default/setting/index.vue
> props warn

- src/locales/lang/zh_CN/sys.ts
- src/utils/http/axios/Axios.ts
- src/utils/http/axios/axiosTransform.ts
- src/utils/http/axios/checkStatus.ts
- src/utils/http/axios/index.ts
- [x ] Is the git submission information standard?
- [ x] I have commented my code, particularly in …
> refactor(axios): requestOptions.errorMessageMode 控制请求周期中通用错误的展示

- src/components/Tree/src/Tree.vue
重构了`Tree`组件空状态显示：
- 空状态样式同其他组件保持一致
- 现在`TreeData`为空时，也会显示空状态，不会影响原有搜索结果空状态控制
> refactor: tree component empty state display

- src/design/ant/index.less
- src/design/theme.less
下面链接在暗黑模式下，勾选样式显示异常
https://vvbin.cn/next/#/comp/table/treeTable
> fix(style): fix checkbox-checked css in dark mode

- src/utils/dateUtil.ts
- [ x] Bug fix (non-breaking change which fixes an issue)
> fix(utils): The date function gets a non-date when the parameter is null

- src/utils/lib/echarts.ts
> fix(echarts): fix graphic config cannot be used in echarts options

- build/utils.ts
修复vite修改配置文件热更新报错Error: Must provide a proper URL as target
> fix(): 修复修改vite配置文件热更新报错

- CHANGELOG.zh_CN.md
- src/logics/theme/dark.ts
- tailwind.config.js
- [ x ] New feature (non-breaking change which adds functionality)
- [ x ] My code follows the style guidelines of this project
- [ x ] Is the code format correct
- [ x ] Is the git submission information standard?
- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x ] My changes generate no new warnings
- [ x ] I have added tests that prove my fix is effective or that …
> 新增对 tailwindcss 夜间模式机制 的支持

- src/components/Form/src/components/FormAction.vue
> fix: style property of actionColOpt is invalid

- src/components/Tinymce/src/Editor.vue
Tinymce上传图片的位置是在最后面，应当是在光标处插入才对
与此issue相关 #986 
> fix: the position of tinymce upload image is wrong

- src/components/Table/src/components/TableHeader.vue
- Bug fix (https://github.com/anncwb/vue-vben-admin/issues/1022)
> fix():  The Style of tableTitle slot

- src/hooks/web/useMessage.tsx
> fix(type): fix ant-design-vue types

- src/components/Icon/src/IconPicker.vue
无需在Change事件中修改绑定的Value。
仅需在属性中设置 v-model:value，选择图标后，value值自动修改。
> IconPicker组件添加v-model:value双向绑定的支持

- src/store/modules/permission.ts
> chore(permission): fix func name typo

- README.zh-CN.md
> docs: Readme增加后台整合示例

- src/components/Modal/src/hooks/useModal.ts
fix (modal):  修复对话框 hook 不设置 loaded问题
> fix (modal):  修复对话框 hook 不设置 loaded问题

- src/components/Modal/src/BasicModal.vue
> fix: 修复弹窗全屏按钮异常关闭的问题(#1177)

- src/components/Menu/src/BasicMenu.vue
修复当路由所在菜单路径是嵌套并且隐藏时无法正常高亮根菜单节点的问题。
Fixed #1080
> fix: 当前路由所在菜单路径是嵌套并且隐藏时无法正常高亮根菜单节点

- src/components/Form/src/components/ApiSelect.vue
> fix: 修复ApiSelect属性被覆盖的问题

- src/components/Upload/src/UploadModal.vue
- src/components/Upload/src/props.ts
- src/utils/http/axios/Axios.ts
1. 兼容`name`属性，用于自定义发到后台的文件参数名; 
2. 增加`filename`属性，用于上传Blob类型时自定义文件名；
> feat(Upload): 兼容ant-design-vue的upload属性

- build/script/buildConf.ts
增加CreateConfigParams接口，并修改createConfig参数默认值
> style(buildConf.ts): 增加函数接口和修改默认的

- src/store/modules/multipleTab.ts
- types/vue-router.d.ts
> 动态路由 Tab打开数量控制，超出限制自动关闭起始Tab

- src/components/Form/src/types/form.ts
> form的label属性实际上可以使用VNode

- src/components/Form/src/hooks/useFormEvents.ts
> fix: Form appendSchemaByField移除hasInList判断

- src/components/Table/src/hooks/useDataSource.ts
> fix(table): 使用lodash 的merge来递归assign,优化在多对象嵌套情况下的结构

- .vscode/extensions.json
> chore: Update extensions.json 

- src/layouts/default/header/components/Breadcrumb.vue
- 修复 hideMenu 路由在 Breadcrumb 下意外点击跳转问题
- Fix the problem of accidentally clicking on the hideMenu route under Breadcrumb to jump
> fix: Fix setting hideMenu, bread bar jump problem

- src/components/Table/src/hooks/useTableScroll.ts
> chore: fix typo

- src/api/demo/table.ts
- src/components/Page/src/PageWrapper.vue
- src/hooks/event/useWindowSizeFn.ts
- src/utils/cache/storageCache.ts
- src/utils/factory/createAsyncComponent.tsx
- src/views/dashboard/analysis/components/GrowCard.vue
- src/views/dashboard/analysis/components/SalesProductPie.vue
- src/views/dashboard/analysis/components/VisitAnalysis.vue
- src/views/dashboard/analysis/components/VisitAnalysisBar.vue
- src/views/dashboard/analysis/components/VisitRadar.vue
- src/views/dashboard/analysis/components/VisitSource.vue
- src/views/dashboard/workbench/components/ProjectCard.vue
- src/views/dashboard/workbench/components/QuickNav.vue
1. `src/views/dashboard/analysis/components/VisitAnalysis.vue` 中的 `props` 引入放到了独立的 `script` 标签里，因为 `lint:eslint` 时触发了 `vue/valid-define-props`[https://eslint.vuejs.org/rules/valid-define-props.html] 校验错误。
```ts
<script lang="ts">
import { basicProps } from './props';
</script>
```
2. 同时，`stylelint` 也报出了 `Unknown word  CssSyntaxError`，未能找到报错原因。由于并未更改css，提交时跳过了此校验
> refactor(dashboard): adjust the spacing of Card under the small screen

- pnpm-lock.yaml
- src/layouts/default/tabs/useMultipleTabs.ts
> Fix Layout Page Tabs dragable

- src/utils/helper/treeHelper.ts
> fix(treeHelper): 修复  listToTree 方法 parent 获取 children 问题

- src/components/Markdown/src/MarkdownViewer.vue
> fix(function):增加 defineProps 引用

- vite.config.ts
> fix(Modal): 修复打包后弹窗在最新的360浏览器13和搜狗失效的问题 (#1381)

- src/hooks/web/useTabs.ts
- [x ] Is the git submission information standard?
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the …
> fix: 修复多tab带参数匹配不正确的bug

- src/components/Table/src/components/editable/EditableCell.vue
修复可编辑表格不显示0的bug，同时又不影响单元格为空触发编辑
> FixEditcell: 修复可编辑单元格不显示0的bug

- src/components/Modal/src/components/Modal.tsx
cancel没有emit导致弹窗无法通过esc和点击遮罩层关闭
#1444 
#1504
> fix(Modal): repair cancel event missing

- src/views/sys/lock/useNow.ts
> fix:修复锁屏界面日期和星期显示问题(#1539)

- src/components/Table/src/BasicTable.vue
- src/components/Table/src/hooks/useScrollTo.ts
- src/components/Table/src/hooks/useTable.ts
- src/components/Table/src/types/table.ts
- 数据加载完毕后需要在视口中显示某一条数据，则可以调用该滚动函数 `scrollTo`
- 当用户调用 `insertTableDataRecord` 插入数据，成功后则可以调用该滚动函数 `scrollTo` 将视口滚动到插入的数据所在位置
> feat(table component): add 'scrollTo' table action

- src/components/Table/src/BasicTable.vue
- src/components/Table/src/hooks/useTable.ts
- src/components/Table/src/hooks/useTableExpand.ts
- src/components/Table/src/types/table.ts
- 在使用树形表格时，时常会需要控制某一项展开（进入页面后根据条件，展开某几项）
> feat(table component): add 'expandRows' table action

- src/enums/httpEnum.ts
> docs(enums): update description

- src/components/Form/src/hooks/useLabelWidth.ts
- I just changed the `Form Item` style, so I didn't create the test file.
- If i use `Form` layout `vertical `,  `Form Item` width is not 100%. This not like ant-design `Form`. That's why I started this PR.
> fix(form component): fix form 'vertical' layout row width

- src/components/Form/src/helper.ts
- src/components/Form/src/hooks/useFormEvents.ts
> fix: 修复表单重置某些input类型组件不生效问题，close #1519

- src/utils/http/axios/Axios.ts
> fix: The value of ignoreCancelToken is not available in headers

- tsconfig.json
> tsconfig 增加 types , 解决webstorm提示错误

- src/components/Container/src/collapse/CollapseHeader.vue
> fix: 修复CollapseContainer组件按钮插槽问题，close #1555

- src/components/Table/src/components/editable/EditableCell.vue
- src/components/Table/src/types/table.ts
- src/views/demo/table/EditCellTable.vue
1. 增加可编辑单元格非编辑状态下可自定义样式
2. 扩展editComponentProps，可接受方法
> feat: 增强可编辑单元格功能

- src/components/Table/src/hooks/useColumns.ts
> fix: 修复Table当dataIndex为数组时，列设置中勾选列是否展示时使column结构异常的问题

- src/components/Form/src/hooks/useFormEvents.ts
1. 兼容appendSchemaByField和updateSchema支持设置默认值
> feat(form): 兼容appendSchemaByField和updateSchema支持defaultValue设置默认值

- src/components/ContextMenu/src/ContextMenu.vue
> fix: 修复右键按钮在弹窗下层级问题

- mock/sys/user.ts
- src/api/sys/user.ts
- src/locales/lang/en/routes/demo.ts
- src/locales/lang/zh-CN/routes/demo.ts
- src/router/routes/modules/demo/feat.ts
- src/utils/http/axios/Axios.ts
- src/utils/http/axios/axiosRetry.ts
- src/utils/http/axios/axiosTransform.ts
- src/utils/http/axios/index.ts
- src/views/demo/feat/request-demo/index.vue
- types/axios.d.ts
> feat: add request retry

- src/design/ant/index.less
- src/views/demo/form/index.vue
- src/views/demo/page/form/high/index.vue
> perf: remove ant-design-vue@3.0.0-beta.11 .ant-col fix

- src/utils/cache/memory.ts
这里要改一下，否则过期不起作用，不知道改的对不对，还有一个毫秒和秒的统一问题
> fix: wrong item.time without the "expires"

- src/components/Application/src/AppLocalePicker.vue
- src/components/Table/src/components/settings/SizeSetting.vue
- src/layouts/default/header/components/lock/LockModal.vue
- src/layouts/default/tabs/components/TabContent.vue
- src/layouts/default/tabs/index.less
- src/views/dashboard/analysis/components/VisitRadar.vue
- src/views/dashboard/workbench/components/SaleRadar.vue
- src/views/demo/charts/SaleRadar.vue
- src/views/demo/feat/request-demo/index.vue
- src/views/demo/page/form/basic/data.ts
- src/views/demo/page/form/basic/index.vue
> fix: 修复控制台一些常见报错和警告

- src/utils/cache/memory.ts
> fix: Set cache overflow of the setTimeout Maximum delay value

- src/components/Application/src/AppLocalePicker.vue
- src/components/Table/src/components/settings/SizeSetting.vue
> fix: 修复 Dropdown 组件 bottomCenter 参数变更，控制台的报错提示

- src/layouts/default/tabs/index.less
- src/views/demo/page/form/step/data.tsx
> pref: Optimize tabs dropdown-menu style

- src/components/Form/src/BasicForm.vue
> feat: 实时监听form表单项值变化

- src/design/transition/fade.less
> fix(Transition): fade-transition淡出淡入无效

- src/components/Description/src/Description.vue
> fix: 修复Description组件渲染function xxxx() { [native code] }的问题

- src/components/Form/src/hooks/useFormValues.ts
> fix: 修复updateSchema之后会把已填值重置为defaultValue的问题

- src/components/Tree/src/Tree.vue
> fix: 修复Tree组件如果重新定义fieldNames的title字段后设置actionList失效的问题

- package.json
- pnpm-lock.yaml
修改`@vue/compiler-sfc`版本为`^3.2.33`，使其和`vue`版本保持同步。
> fix: update @vue/compiler-sfc version

- src/views/demo/permission/back/Btn.vue
- src/views/demo/permission/back/index.vue
> fix: fix wrong naming

- src/components/Table/src/types/pagination.ts
> feat: specify the position of Pagination in Table component

- src/components/Table/src/components/settings/SizeSetting.vue
```
[VueTypes warn]: oneOf - value should be one of "topLeft", "topCenter", "topRight", "bottomLeft", "bottomCenter", "bottomRight".
[Vue warn]: Invalid prop: custom validator check failed for prop "placement".
```
> fix: custom validator check failed for prop "placement"

- src/components/Tree/src/Tree.vue
- src/components/Tree/src/tree.ts
- src/components/Tree/src/useTree.ts
- src/views/demo/tree/ActionTree.vue
> feat(function): get selected tree node

- src/components/Table/src/components/settings/SizeSetting.vue
> fix: dropdown placement bottomCenter to bottom

- src/components/Table/src/hooks/useColumns.ts
> fix/invaild dateFormat

- src/router/routes/modules/about.ts
> perf: Changing variable names

- src/components/Form/src/hooks/useFormEvents.ts
- src/components/Table/src/hooks/useColumns.ts
> fix(useFormEvents): isNullOrUnDef is not defined

- src/views/sys/login/LoginForm.vue
> style: fix style error of login page

- pnpm-lock.yaml
- src/utils/lib/echarts.ts
- [*] Pull request template structure not broken
- [* ] Bug fix (non-breaking change which fixes an issue)
- [* ] My code follows the style guidelines of this project
- [* ] Is the code format correct
- [* ] Is the git submission information standard?
- [* ] My code follows the style guidelines of this project
- [* ] I have performed a self-review of my own code
- [* ] My changes generate no new warnings
> fix(echarts): 修复无法使用散点图表

- src/components/ContextMenu/src/ContextMenu.vue
- src/components/ContextMenu/src/typing.ts
- src/components/Table/src/components/settings/SizeSetting.vue
- src/components/Tree/src/Tree.vue
- src/components/Tree/src/tree.ts
> feat: contextMenuItem add hidden property

- src/views/demo/page/account/center/data.tsx
> fix: 个人中心（data.tsx）多余的html片段

- .gitignore
- src/main.ts
- src/router/index.ts
- src/router/routes/index.ts
> docs: 尝试添加注释

- src/components/Table/src/components/settings/ColumnSetting.vue
> fix(ColumnSetting): 修复默认隐藏列拖拽排序错误的问题

- src/hooks/core/useContext.ts
> feat(useContext): 删除多余重载

- src/hooks/web/usePage.ts
> types: 修复RouteLocationRawEx类型错误 (vbenjs#1968)

- src/components/Table/src/components/settings/ColumnSetting.vue
> fix: 修复表格列设置下拉框中偶现列数据区域空白 (#1958)

- .vscode/settings.json
- src/components/Table/src/components/settings/ColumnSetting.vue
> types: 缩减 setup script 警告 & 修复表格列设置组件中部分方法参数类型错误.

- src/hooks/web/usePage.ts
> types: 再次修复RouteLocationRawEx类型错误 (vbenjs#1968)

- src/components/Modal/src/index.less
修复原版antdv的`Modal`高度因为vben `Modal`样式发生高度不匹配的问题，修复后vben的`Modal`保持样式不变。
> style: 修复antdv Modal header高度错误

- src/components/Table/src/BasicTable.vue
- src/views/demo/table/CustomerCell.vue
> feat(function): add table bodyCell slot for antdv3.x; and fix #1705

- src/views/demo/system/account/AccountModal.vue
- src/views/demo/system/dept/DeptModal.vue
- src/views/demo/system/password/index.vue
- src/views/demo/system/role/RoleDrawer.vue
> style: 优化系统管理中账号、角色和部门表单样式

- src/layouts/default/header/components/user-dropdown/index.vue
> fix: type warning.

- src/design/index.less
- src/views/demo/editor/tinymce/Editor.vue
> 修改tinymce富文本下拉菜单错位的bug

- src/design/index.less
- src/views/demo/editor/markdown/Editor.vue
- src/views/demo/editor/tinymce/Editor.vue
> 修复tinymce嵌入表单示例页面换行错误，清理!important，revert(vbenjs#1996)

- src/views/demo/system/password/pwd.data.ts
> fix: password rules validator tips

- src/components/Drawer/src/components/DrawerFooter.vue
> fix: 修复DrawerFooter border-top导致滚动条出现的问题

- src/components/Form/src/hooks/useFormEvents.ts
> fix: 更新Schema时默认值不应覆盖已有值，fix #1997

- .vscode/extensions.json
> fix: Update extensions.json for volar identifier

- src/components/Table/src/components/editable/EditableCell.vue
- src/components/Table/src/hooks/useTableScroll.ts
- src/components/Table/src/types/table.ts
- src/hooks/component/useFormItem.ts
Co-authored-by: Cyrus Zhou <6802207@qq.com>
使用方式同 Form FormSchema dynamicDisabled
```
export const Columns: BasicColumn[] = [
{
title: 'Title',
dataIndex: 'Title',
editRow: true,
editComponent: 'Select',
editDynamicDisabled: ({ record }) => record.isDisabled,
},
> Table BasicColumn 添加 editDynamicDisabled

- src/components/Table/src/hooks/useTableFooter.ts
I noticed there was no synchronous scrolling, so I fixed it
I'm wondering if I need to unscroll the total line, let me know if I need to
> fix(useTableFooter): not synchronization scroll bug

- src/components/Markdown/src/Markdown.vue
- src/components/Markdown/src/MarkdownViewer.vue
- src/components/Markdown/src/getTheme.ts
- src/views/demo/editor/markdown/index.vue
> fix: markdown深色模式内容区和代码块未适配bug; markdownViewer改为vidtor自带预览模式

- src/components/Table/src/components/editable/EditableCell.vue
- [x ] Is the git submission information standard?
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] My changes generate no new warnings
> fix: fix#2031 修复表格可编辑行在编辑模式下，无法处理数组类型的值的问题

- src/hooks/web/usePage.ts
对当前页面重新加载多次，会导致点击浏览器后退或前进按钮之后任然停留在当前页面
> fix(useRedo): 重新加载页面useRedo方法会添加一条浏览记录

- commitlint.config.js
- package.json
- yarn.lock
Hi 我是`cz-git`的作者，偶然之间查看项目，虽然有引入 commitizen 但未使用，我觉得我的`cz-git`应该可以很大帮助使用 commitizen CLI 的使用者。当然这也是我第一次给完整系统提供解决方案 PR 。如果有其他需求点可以和我说。
- github: https://github.com/Zhengqbbb/cz-git
- website: https://cz-git.qbenben.com/
- 中文文档： https://cz-git.qbenben.com/zh/
---
- **友好型**： 支持搜索和选择在命令行中，减少拼写错误
- **高度自定义**：提供全套的自定义，让 CLI 行为更符合习惯操作
- **与 commitlint 配合**：获取 commitlint 相关配置，给予命令行提示信息
- **轻量级**：正如你所见，整体依赖都下降了许多，`czg`(1.3 MB) 和 `cz-git`(1.5 MB) …
> chore: use `cz-git` commitizen adapter

- src/utils/helper/tsxHelper.tsx
> 修复使用`extendSlots`辅助函数时插槽参数未传递的问题。

- mock/_util.ts
- src/enums/httpEnum.ts
- [ x] I have commented my code, particularly in …
> fix: 使用枚举属性表示mock的响应状态

- src/design/ant/input.less
> fix: inputnumber span 不起作用的问题，增加样式之后可以根据Span动态适应

- build/vite/plugin/styleImport.ts
**当我使用`ImagePreviewGroup`的时候，build时发生了一个错误，我看了依赖后才发现，这个子组件应该是要使用image/style/index 的css文件才对**
> fix(styleImport): fix ImagePreviewGroup build error

- src/components/Table/src/BasicTable.vue
Reverts vbenjs/vue-vben-admin#1978
加了这个样式后，有操作栏的表格会产生bug。
> Revert "style: 优化滚动条显示，只有在内容超过显示高度时才会出现"

- src/components/Table/src/hooks/useColumns.ts
> fix: 修改表格的resizeColumn事件的回调函数中，修改列宽度无效的bug (vbenjs#2073)

- src/utils/http/axios/index.ts
> fix(axios): 非GET请求时增加判断config.data是否为FormData

- src/views/sys/login/Login.vue
…ty is true
- [x ] Pull request template structure not broken
> fix(Login): fix display issues when AppLocalePicker's showText property is true.

- src/layouts/page/index.vue
- src/views/demo/table/Basic.vue
fix: #2052 Resulting error
keep-alive disabler 
> fix(keep-alive): disabler

- src/components/SimpleMenu/src/SimpleSubMenu.vue
> fix: 修复SimpleSubMenu组件被意外地重新渲染的bug (#2106)

- src/components/Form/src/hooks/useAdvanced.ts
> fix: 修改BasicForm表单的展开和收起按钮状态错误的bug (#2089)

- src/components/ContextMenu/src/ContextMenu.vue
> fix: 右键组件缺少PropType类型引用

- src/components/Excel/src/Export2Excel.ts
> fix: excel export set width

- src/components/Form/src/components/ApiTransfer.vue
> types(components): ApiTransfer  props 类型错误，删除多余属性

- src/components/Cropper/src/CropperAvatar.vue
- src/views/demo/page/account/setting/BaseSetting.vue
未更改前上传头像组件,返回的是base64编码,但是有些在后端保存的是url,现增加data属性,base64和后端返回值都能用
> perf: 头像上传组件返回值增加后端接口的返回值

- src/components/Table/src/BasicTable.vue
- src/design/ant/index.less
> 表格查询条件下拉框文本超长显示错乱

- src/utils/http/axios/index.ts
> fix: 修复在取消重复请求时，错误处理

- src/components/Form/src/BasicForm.vue
- src/components/Form/src/hooks/useForm.ts
- src/components/Form/src/hooks/useFormEvents.ts
- src/components/Form/src/types/form.ts
- src/views/demo/form/AppendForm.vue
- src/views/demo/form/DynamicForm.vue
> fix: 修复单词拼写错误，replace 'Filed' with 'Feild'

- .husky/commit-msg
- .husky/pre-commit
> fix: 解决mac系统提交代码环境变量报错问题

- .gitignore
> fix: vscode安装本地缓存插件后，项目根目录下会生成.history文件夹，忽略提交

- src/router/constant.ts
> fix: 修复getParentLayout方法接受了参数，但并没有用上

- src/components/Button/src/BasicButton.vue
- src/components/Button/src/props.ts
> refactor: 重构button代码props的引入方式，获取更优雅的类型提示

- src/components/Form/src/hooks/useFormValues.ts
> fix(form): 修复表单fieldMapToTime对应的值为空仍提交原来的字段值

- src/store/modules/multipleTab.ts
> fix: 关闭非当前的标签没有同步清理cacheTabList数据

- types/vue-router.d.ts
> fix: 修复RouteMeta接口定义缺少的RoleEnum引用

- src/design/ant/input.less
扩展自#2065，让增加了 前置/后置标签的inputNumber 也能根据span动态适应
> fix: inputNumberGroup(前置/后置标签) span 不起作用的问题，增加样式之后可以根据Span动态适应

- src/locales/lang/en/sys.ts
- src/locales/lang/zh-CN/sys.ts
- src/utils/http/axios/index.ts
- types/axios.d.ts
> feat(axiosSuccess): 操作成功后根据传入提示模式进行相应

- src/components/Table/src/BasicTable.vue
- src/components/Table/src/hooks/useTable.ts
- src/components/Table/src/types/table.ts
- [✅ ] Pull request template structure not broken
- [✅  ] Bug fix (non-breaking change which fixes an issue)
> 表格添加一个setRows方法以便数据回显后重新获取数据#1571

- src/components/Table/src/BasicTable.vue
修复#2327 新增方法 setSelectedRows 引入但未加入 tableAction 
> fix(BasicTable): setSelectedRows 引入但未加入 tableAction 

- src/views/dashboard/workbench/components/data.ts
> fix: fix typo

- src/components/Excel/src/Export2Excel.ts
> fix(component/Excel): 解决导出excel时数据某一项为null时计算宽度的报错

- src/utils/http/axios/index.ts
> fix: 统一errorMessageMode值为单引号

- src/utils/dateUtil.ts
> fix(utils): fix dateUtil.formatToDate ts type

- src/utils/dateUtil.ts
抱歉发现昨天的pr https://github.com/vbenjs/vue-vben-admin/pull/2345 少改了一个函数，而且从老的history多copy了一行进去
> fix(utils): fix dateUtil.formatToDate/formatToDateTime ts type

- src/components/Excel/src/ImportExcel.vue
> fix: 修复导入相同excel文件不发生change事件

- src/layouts/default/setting/components/ThemeColorPicker.vue
- src/layouts/default/setting/components/TypePicker.vue
> fix: props 定义默认值拼写错误 defualt => default

- src/components/Form/src/props.ts
- src/components/Menu/src/props.ts
- src/components/Tinymce/src/Editor.vue
- src/components/Upload/src/props.ts
- src/components/Verify/src/props.ts
> fix: 修复props默认字段default返回空对象语法问题

- README.md
- README.zh-CN.md
- src/router/routes/modules/demo/system.ts
> The link of document had been expired

- src/router/routes/modules/demo/system.ts
> fix: views中country目录不存在

- src/components/Preview/src/Functional.vue
> fix: #2390 [Preview]缩小后scale为负值

- src/components/Table/src/components/TableImg.vue
> fix: 修复表格图片插槽margin不生效问题

- src/components/Form/src/hooks/useFormEvents.ts
> 处理(Warning 'Use of eval is strongly discouraged')警告

- src/components/Form/src/hooks/useFormEvents.ts
> fix: 修复频繁调用_setDefaultValue方法，设置初始值的时候，多次调用失效的问题

- src/components/Form/src/props.ts
> fix: 修复Form组件emptySpan类型定义错误

- src/components/Table/src/BasicTable.vue
- [x ] Pull request template structure not broken
- [x ] Is the git submission information standard?
- [x ] I have performed a self-review of my own code
- [x ] My changes generate no new warnings
- [x ] I have added tests that …
> fix:增加basictable组件name，防止注册组件的时候组件没有name

- README.md
- README.zh-CN.md
> chore: change website link

- README.md
fix(docs): explicitly checkout the thin branch
> fix(docs): explicitly checkout the thin branch

- src/components/Table/src/components/editable/EditableCell.vue
> fix: table cell edit bug.

- src/components/Table/src/components/editable/EditableCell.vue
> fix(components): [Table,EditableCell] rename Function

- src/components/Table/src/hooks/useDataSource.ts
- src/components/Table/src/types/table.ts
> 优化table组件的insertTableDataRecord增加批量导入的功能

- src/components/Table/src/hooks/useDataSource.ts
> fix: table-datasource，如果后端返回的page total是字符串，会导致页码乱掉

- .gitattributes
> build: git config

- src/components/Form/src/hooks/useFormEvents.ts
- src/views/demo/form/RuleForm.vue
> feat: 使用useForm时调用setFieldsValue后，组件的onChange未主动触发 (#2142)

- src/components/Table/src/hooks/useDataSource.ts
- src/components/Table/src/types/table.ts
> fix: 修复table组件insertTableDataRecord方法的返回类型

- mock/sys/menu.ts
- src/router/routes/modules/demo/iframe.ts
- src/settings/siteSetting.ts
- src/views/sys/login/QrCodeForm.vue
> fix:修复header下拉菜单和外部页面菜单的文档链接

- src/components/Dropdown/src/Dropdown.vue
- src/components/Form/src/props.ts
- src/components/Preview/src/Functional.vue
- src/components/Table/src/props.ts
- src/components/Upload/src/props.ts
> fix: 修复props中Array类型定义问题

- src/views/demo/form/AppendForm.vue
fix(AppendForm): 修复 批量添加表单配置 按钮点击事件未使用批量方法 问题
perf(AppendForm): 表单排版改用baseColProps一次配置，减少重复代码
> fix(AppendForm): 修复 批量添加表单配置 按钮点击事件未使用批量方法 问题; 表单排版改用baseColProps一次配置，减少重复代码

- src/hooks/component/useFormItem.ts
> fix:  修复表单自定义组件验证不通过的bug

- src/utils/index.ts
> chore: fix type

- src/views/demo/table/MergeHeader.vue
- src/views/demo/table/tableData.tsx
> fix: 合并单元格页面 由于 ant-design-vue 升级 v3 版本，页面报 Warning: columns.customRender 即将废弃，columns.customRender 用 columns. customCell 替换

- src/components/Table/src/hooks/useColumns.ts
- src/views/demo/table/EditRowTable.vue
> fix(useColumns): 多级表头下的列支持行内编辑

- src/hooks/event/useBreakpoint.ts
> docs：optimization point notes

- src/components/VxeTable/src/VxeBasicTable.tsx
- src/components/VxeTable/src/methods.ts
- src/views/demo/table/VxeTable.vue
> perf(vxetable): 封装方法中加入可编辑表格和表单验证相关方法名，并在demo中增加新增和删除方法调用实现

- src/views/sys/login/useLogin.ts
> feat<useLogin>: original Form.validate

- vite.config.ts
> fix: 修复esbuild的drop_console

- src/components/Table/src/components/TableAction.vue
- src/views/demo/table/VxeTable.vue
1. fix(TableAction): 修复outside模式引用时报错: TypeError: Cannot read properties of undefined (reading 'value')
2. perf(VxeTable): demo引用TableAction改为outside模式以解决警告; 属性添加keepSource以解决警告 #2540
> fix(TableAction): 修复outside模式引用时报错；VxeTable demo引用TableAction改为outside模式, 属性添加keepSource以解决警告

- src/views/demo/page/form/high/PersonTable.vue
> fix<table>: 高度丢失

- src/components/Table/src/types/table.ts
> chore<table>: fix type

- src/components/Table/src/props.ts
> chore<table>:  fix type

- src/views/sys/login/useLogin.ts
> docs: optimization point notes

- src/utils/color.ts
> fix<utils>: Color Regular Error

- src/components/Container/src/collapse/CollapseContainer.vue
> refactor: collapse/CollapseContainer

- src/components/Container/src/collapse/CollapseHeader.vue
> refactor： 插槽优先属性调整，prefixCls优先关系调整

- src/views/demo/feat/full-screen/index.vue
> fix: 重复点击全屏会抖动

- src/views/demo/page/form/high/PersonTable.vue
> fix: table 高度消失

- src/views/demo/page/form/high/index.vue
> fix: css !mt-5

- src/views/demo/table/FormTable.vue
> fix(FormTable): fix table spread selection(#2565)

- mock/_createProductionServer.ts
> refactor<mock>: compatibility notes

- src/views/demo/form/UseForm.vue
> refactor<useForm>: 重构案例

- src/components/Form/src/components/FormItem.vue
> fix: 组件属性优先默认

- src/components/Container/src/collapse/CollapseHeader.vue
> fix: 修复Container中头部组件插槽中的action不生效的问题

- src/components/Container/src/collapse/CollapseContainer.vue
> fix<CollapseContainer>: v-show 才不会丢失目标容器

- src/hooks/web/useMessage.tsx
> fix: 修复消息hooks icon类型

- src/views/demo/form/UseForm.vue
> refactor: 重构案例代码

- src/components/Icon/src/IconPicker.vue
> fix: 解决IconPicker初始拷贝了value的值，导致剪切板内容被覆盖

- src/components/Container/src/collapse/CollapseHeader.vue
> fix<CollapseHeader>: CollapseHeader action 插槽

- src/utils/index.ts
> fix: 修复deepMerge方法问题

- src/components/Modal/src/BasicModal.vue
> fix: 解决BasicModal弹窗动态:wrapClassName属性被useFullScreen hooks覆盖的问题

- src/components/Table/src/BasicTable.vue
- src/components/Table/src/components/settings/ColumnSetting.vue
表格显示列是异步加载数据时，ColumnSetting里的watchEffect监听表格列不生效，导致异步加载的表格列数据无法在表格设置上显示。
相关issue：[#2257](https://github.com/vbenjs/vue-vben-admin/issues/2257)，[#1630](https://github.com/vbenjs/vue-vben-admin/issues/1630)
> fix: 修复异步加载表格列时，表格设置显示列为空

- src/components/Form/src/hooks/useFormEvents.ts
> fix: 修复表单验证失败的多个错误提示，语法报错问题

- src/components/Tree/src/hooks/useTree.ts
> fix:修复树获取children出错

- src/components/Table/src/BasicTable.vue
- src/components/Table/src/components/settings/ColumnSetting.vue
表格设置单击固定某一列时，@columns-change事件回调的数据未检查过滤当前的checklist，导致所有的表格回调数据的visible属性都为true
> 修复表格设置固定列，事件回调数据错误

- src/components/Form/src/hooks/useFormEvents.ts
> fix: 修复TypeError: item.indexOf is not a function报错

- src/components/VxeTable/src/components/AApiTreeSelect.tsx
- src/components/VxeTable/src/components/index.tsx
> fix: vxe-table与vben ApiTreeSelect适配，解决vxe-table检索表单不显示AApiTreeSelect的问题

- src/components/Form/src/components/ApiTransfer.vue
> fix: ApiTransfer的targetKeys属性无效

- src/components/Form/src/BasicForm.vue
- src/components/Form/src/components/FormItem.vue
- src/components/Form/src/helper.ts
- src/hooks/component/useFormItem.ts
- src/views/demo/form/index.vue
1.优化验证，setFormModel方法禁止多次验证
2.修复自定义组件验证出错的问题
> fix: 修复表单验证

- src/hooks/web/useWatermark.ts
> fix: 修复水印重复叠加问题

- src/components/Button/src/props.ts
> perf(BasicButton): 按钮颜色设置支持主题色primary

- src/components/VxeTable/src/componentMap.ts
- src/views/demo/table/VxeTable.vue
> feat: 替换vextable中button组件

- src/components/Modal/src/components/ModalHeader.vue
> fix: modalheader dblclick

- src/components/Upload/src/helper.ts
> fix: upload component preview .webp image

- src/views/demo/form/UseForm.vue
> feat: 添加更多配置项

- src/components/Form/src/components/ApiSelect.vue
> fix(ApiSelect): 支持x.x.x格式

- src/utils/index.ts
> refactor: deepMerge

- src/hooks/web/useECharts.ts
> fix(hooks): 修改在使用useEcharts时, getInstance无法获取到最新的echarts实例方法返回值的问题, 例如: getDataURL()、getOption()等

- src/components/Form/src/hooks/useFormEvents.ts
解构Field初始化value.
```
useForm({
schema: [{
field: '[lng, lat]',
onChange(value) {
console.log(value); // [100, 200]
}
....
}]
})
// 支持初始化
setFieldsValue({
lng: 100,
lat: 200
});
```
- [ X] Pull request template structure not broken
- [ X] New feature (non-breaking change which adds functionality)
- [X ] My code follows the style guidelines of this project
- [ X] Is the code format correct
- [ X] Is the git submission information …
> feat: 解构字段设置value

- src/views/form-design/components/VFormDesign/modules/CollapseItem.vue
> fix(form-design): CollapseItem组件页面css添加prefixCls前缀, 防止打包后污染全局样式

- src/components/Form/src/hooks/useFormEvents.ts
> fix(useFormEvents): 修复#2648 修改导致的末尾大括号丢失

- src/layouts/default/setting/components/SettingFooter.vue
> fix(项目配置): 修复 #2652 重置项目配置，导致左侧菜单栏整体变成白色

- src/components/Excel/src/Export2Excel.ts
- src/components/Excel/src/typing.ts
- src/views/demo/excel/ArrayExport.vue
- src/views/demo/excel/JsonExport.vue
feat(excel导出): 增加批量导出功能, 增加demo示例
> feat(excel导出): 增加批量导出功能, 增加demo示例

- src/utils/propTypes.ts
> fix: propTypes.extend()方法已经废弃, 改为官方推荐的ES6+方法

- src/utils/index.ts
#2660 #2663 这些issues提出的问题就是这个bug导致的
> fix(deepMerge): 修复递归合并操作, 合并数组未去重的bug

- src/components/Form/src/hooks/useFormEvents.ts
```ts
const [_, { setFieldValues }] = useForm({
schema: [
{
field: 'foo[0].bar',
componentOptions: {
onChange(val) {
console.log(val); // the bar 1
}
}
},
{
field: 'foo[1].bar',
componentOptions: {
onChange(val) {
console.log(val); // the bar 2
}
}
}
]
})
setFieldValues({
foo: [{  bar: 'the bar 1' }, {  bar: 'the bar 2' }],
})
```
> 👉 _Put an `x` in the boxes that …
> feat: 多路径字段获取值

- src/hooks/component/useFormItem.ts
> fix(useFormItem):修复ApiSelect的onChange事件获取不到第二个参数(#2592)

- tsconfig.json
> perf: tsconfig 同步vite配置修改, 增加路径映射

- src/components/Form/src/hooks/useFormEvents.ts
fix: 方法会导致[undefined, undefined]值覆盖有效值
- [X ] Pull request template structure not broken
- [X ] Bug fix (non-breaking change which fixes an issue)
- [ X] My code follows the style guidelines of this project
- [ X] Is the code format correct
- [ X] Is the git submission information standard?
- [ X] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my own code
- [ X] I have commented my code, …
> fix: 空数组覆盖有效数组

- src/utils/mitt.ts
> feat: sync mitt

- src/utils/http/axios/axiosCancel.ts
> refactor: axios Canceler use AbortController

- src/layouts/default/setting/components/InputNumberItem.vue
> fix: 解决项目配置/界面功能/自动锁屏&菜单展开宽度样式变形问题

- src/directives/ellipsis.ts
- src/directives/index.ts
> feat(directives/ellipsis): add ellipsis directive

- package.json
> fix: 解决打包报内存溢出问题

- internal/eslint-config/src/strict.ts
> chore: 使用`defineConfig`定义eslint配置

- src/store/modules/multipleTab.ts
> fixed:修复操作页签后 打开页面需要使用fullPath，否则可能会导致参数丢失引起数据加载异常。

- src/hooks/web/usePage.ts
- src/router/routes/basic.ts
- src/views/sys/redirect/index.vue
此pr更改前，若路由存在 `params` 参数，在使用 `useRedo` 进行页面刷新会导致 `params` 丢失
简单处理后 `params` 参数可以正常传递
> fix: 解决重定向路径 params 参数丢失问题

- .github/workflows/deploy.yml
> workflow: fix github action build error

- src/components/Form/src/hooks/useFormEvents.ts
> fix: 由于 多路径字段获取值 (#2664) 处理 造成的 set value值为0||''时不成功的情况

- src/views/demo/table/RefTable.vue
- src/views/demo/table/UseTable.vue
本次是对#2745 更改后，改变demo的写法。
[文档修改`pr` ](https://github.com/vbenjs/vue-vben-admin-doc/pull/109)
> perf(demo): 动态更换表格配置

- .github/workflows/deploy.yml
> ci(fix): 修复更新lock文件导致github action失败

- src/api/demo/model/optionsModel.ts
> fix(api/demo): fix model field name typo

- internal/vite-config/src/plugins/appConfig.ts
> fix:删除appConfigSrc多余符号

- src/components/Modal/src/index.less
> perf: 优化modal弹窗样式

- src/components/Tree/src/BasicTree.vue
> perf: 优化tree getIcon方法类型定义

- src/router/routes/basic.ts
解决该提交（ https://github.com/vbenjs/vue-vben-admin/pull/2753 ）中 redirect 路由 params 必传导致的报错问题
> fix: 修复未传参(params)的时，redo失效的问题

- src/utils/index.ts
> fix(deepMerge): fix recursive merge data without removing duplicate bugs

- src/components/Modal/src/index.less
Reverts vbenjs/vue-vben-admin#2824
> Revert "perf: 优化modal弹窗样式"

- src/components/Page/index.ts
- src/components/Page/src/PageWrapper.vue
- src/components/Table/src/BasicTable.vue
- src/enums/pageEnum.ts
yes
- [ x ] New feature (non-breaking change which adds functionality)
- [ x ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ x ] This change requires a documentation update
> fix: 修复 Cannot access 'pagewrapper' before initialization

- src/store/modules/multipleTab.ts
> fix:关闭其它页签需要使用fullPath来判断，更新缓存后需要同时更新localStorage，否则刷新页面页签会再次加载

- src/utils/__test__/index.test.ts
- src/utils/index.ts
> fix(deepMerge): the default merge strategy is to replace the array

- src/utils/index.ts
Reverts vbenjs/vue-vben-admin#2831
> Revert "fix(deepMerge): fix recursive merge data without removing duplicate bugs"

- src/utils/index.ts
> fix(deepMerge): 去掉合并错误的代码

- src/views/demo/system/role/RoleDrawer.vue
- src/views/demo/system/role/role.data.ts
> RoleDrawe.vue 改造为setup,角色编辑时状态不正确

- src/components/Form/src/components/ApiSelect.vue
> fix: 修复当设置apiselect的immediate为false时，默认赋值后取值不正确传入默认options方案

- src/utils/__test__/index.test.ts
- src/utils/index.ts
> fix(utils): 修复deepMerge不能合并第一层非基本数据类型

- internal/ts-config/package.json
> fix: 修复ts-config未匹配上的文件

- .dockerignore
- .env.docker
- Dockerfile
- README.md
- README.zh-CN.md
- internal/vite-config/src/config/application.ts
- internal/vite-config/src/plugins/index.ts
- nginx.conf
- package.json
- pnpm-lock.yaml
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in …
> Docker dynamic publish support.

- internal/vite-config/src/config/application.ts
- internal/vite-config/src/config/common.ts
- internal/vite-config/src/config/package.ts
> feat: esbuild增加不同开发模式下对console debugger的处理

- internal/vite-config/src/plugins/appConfig.ts
- src/utils/env.ts
> 通过把名称编码成hex，使项目能够在VITE_GLOB_APP_TITLE包含特殊字符时正常打包

- src/design/ant/index.less
- src/layouts/default/header/components/notify/index.vue
- src/layouts/default/header/index.less
- src/layouts/default/tabs/components/TabRedo.vue
> fix: 修复部分图标未居中的问题

- src/components/Form/src/hooks/useFormEvents.ts
> feat：不允许可重复添加同一field的表单项

- src/components/Form/src/componentMap.ts
- src/components/Form/src/types/index.ts
- src/views/demo/form/index.vue
> 增加TimeRangePicker时间区间范围选择组件

- src/components/Table/src/components/editable/index.ts
- [ x] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the …
> fix: 修复BasicTable组件开启可编辑行卡顿/卡死问题

- src/components/Dropdown/src/Dropdown.vue
> fix(Dropdown): Dropdown组件在禁用状态仍能弹窗问题;

- src/components/Table/src/hooks/useTableScroll.ts
> chore: split function for easy maintain, understand and using

- src/components/Application/index.ts
- src/design/dark.less
- src/design/index.less
- src/layouts/default/setting/SettingDrawer.tsx
- src/views/sys/login/Login.vue
> feat: 恢复暗黑主题

- src/components/Form/src/components/ApiTreeSelect.vue
解决了这个issure： https://github.com/vbenjs/vue-vben-admin/issues/2268 。代码参考了ApiSelect.vue
> fix: 解决ApiTreeSelect的params更新后fetch不执行

- tsconfig.json
> fix: ts error

- src/design/ant/index.less
fix https://github.com/vbenjs/vue-vben-admin/issues/2957
> fix left/right icon not align to center in BasicTable

- src/enums/cacheEnum.ts
- src/hooks/core/useContext.ts
- src/store/modules/app.ts
- src/utils/http/axios/index.ts
- src/views/sys/login/LoginForm.vue
> refactor: code optimization

- src/components/Tree/src/types/tree.ts
> fix(Tree): beforeRightClick type

- nginx.conf
> chore: format nginx.conf

- src/components/Form/src/hooks/useFormEvents.ts
- src/components/Prompt/dialog.vue
- src/components/Prompt/index.ts
- src/components/Prompt/state.ts
- src/views/demo/comp/modal/index.vue
类似于Element UI组件库的[MessageBox Prompt组件](https://element.eleme.cn/#/zh-CN/component/message-box#ti-jiao-nei-rong)
> feat: 增加Prompt组件,  并且修复 #2976

- src/design/ant/index.less
> fix(msg): message icon not centered

- src/design/ant/index.less
- src/views/demo/table/VxeTable.vue
1. VxeTable demo 参数错误
2. tab标签 关闭图标未居中 closes #2988
> fix: VxeTable demo parameter typo& tabs close icon not centered

- internal/vite-config/src/config/application.ts
fix: env配置文件中`VITE_PUBLIC_PATH`字段无效
> fix: 配置文件公共路径无效

- src/design/ant/index.less
详情drawer组件的左箭头不居中了，https://github.com/vbenjs/vue-vben-admin/pull/2989#issuecomment-1713566380
从这个[commit](https://github.com/vbenjs/vue-vben-admin/commit/f675fff2e66054b4157b2a330dbf151822b0befd)之后一直在打补丁，去掉之后发现包括登录页，图片预览、图标页面等之前有问题的页面问题也不存在
> fix: arrow-left icon not centered

- src/views/demo/form/CustomerForm.vue
fix: 由于更新ant-vue 新版本到 4.0.2以上 tsx 渲染 FormItem 插入style 导致的出错 改换class
> fix: 由于更新ant-vue 新版本到 4.0.2以上 tsx 渲染 FormItem 插入style 导致的出错 改换class

- src/components/Form/src/components/FormAction.vue
> fix: type check failed for prop 'onClick'

- src/components/Table/src/components/settings/ColumnSetting.vue
- src/views/demo/form/UseForm.vue
> fix: visible deprecated warnings

- src/components/Form/src/components/FormAction.vue
> fix: FormAction组件 绑定表单提交事件

- src/api/sys/model/userModel.ts
**Although the role in LoginReulstModel is useless in current login logic, but we think it shoudl be consistent with other model like GetUserInfoModel, ss user should has multiple roles.**
Relevent Issue:
https://github.com/vbenjs/vue-vben-admin/issues/259
> fix: Change role to roles for LoginResultModel

- src/utils/http/axios/Axios.ts
> fix(axios): get等方法配置ignoreCancelToken无效

- nginx.conf
> feat: update nginx.conf 使用固定编译入口可能导致浏览器使用缓存js文件，而此配置可以解决

- src/design/index.less
处理 移动滚动条的时候，ant-select-dropdown 没有随form-item移动
> fix  处理 移动滚动条的时候，ant-select-dropdown 没有随form-item移动

- src/locales/lang/en/common.ts
> fix: 英文版本时提示中的单词没有分开

- src/components/ContextMenu/src/ContextMenu.vue
> fix: Fix context menu style not working

- .github/workflows/node.js.yml
- package.json
> Fix unable to run the clear cache command normally #3086 

- src/components/Form/src/hooks/useFormEvents.ts
- src/components/Form/src/hooks/useFormValues.ts
- src/utils/is.ts
1.修正日期区间拆解时数据为null时异常问题 #3094 
2.修正validate|validateFields时，未将对象型数据进行转换 #3095
> 修正日期区间拆解时数据为null时异常问题/修正validate|validateFields时，未将对象型数据进行转换

- src/components/Form/src/components/ApiSelect.vue
https://github.com/vbenjs/vue-vben-admin/issues/2830
https://github.com/vbenjs/vue-vben-admin/issues/2738
> fix(ApiSelect):  移除watchEffect引发的重复请求

- src/components/Table/src/components/editable/EditableCell.vue
> fix: tabel取消编辑单元格后会回到初始值. close #2739

- internal/vite-config/package.json
- internal/vite-config/src/plugins/appConfig.ts
- internal/vite-config/src/plugins/index.ts
- internal/vite-config/src/utils/hash.ts
- pnpm-lock.yaml
> refactor: use `unplugin-config`

- src/components/Form/src/BasicForm.vue
- src/components/Form/src/hooks/useForm.ts
- src/components/Scrollbar/src/util.ts
- src/logics/mitt/routeChange.ts
- src/utils/bem.ts
> chore: Fix ts type error

- internal/vite-config/package.json
- internal/vite-config/src/plugins/appConfig.ts
- pnpm-lock.yaml
Reverts vbenjs/vue-vben-admin#3116
> Revert "chore: update `unplugin-config`"

- src/components/Excel/src/ExportExcelModal.vue
- src/components/Form/src/types/form.ts
> fix(customExport): Failure to export

- src/api/demo/model/tableModel.ts
- src/components/Form/src/hooks/useForm.ts
- src/components/Form/src/types/form.ts
- src/components/Markdown/src/MarkdownViewer.vue
- src/components/Table/src/components/settings/SizeSetting.vue
- src/components/Tree/src/hooks/useTree.ts
- src/views/demo/page/form/high/PersonTable.vue
- src/views/demo/table/EditRowTable.vue
- src/views/form-design/components/VFormCreate/index.vue
- src/views/form-design/hooks/useFormInstanceMethods.ts
- src/views/form-design/hooks/useVFormMethods.ts
- types/global.d.ts
> chore: fix type:check error

- src/layouts/default/header/components/lock/LockModal.vue
> fix(LockModal): Cannot unlock

- src/components/Drawer/src/components/DrawerFooter.vue
fix: #3144  Drawer的footer样式错位问题
> fix: #3144 Drawer的footer样式错位问题

- src/components/Form/src/components/ApiTransfer.vue
> fix: ApiTransfer 不支持disabled

- src/hooks/web/useMessage.tsx
> fix: 修复Modal.confirm的返回类型问题，需要有destroy，update的方法

- package.json
- pnpm-lock.yaml
> chore(deps): updated ant-design-vue to version 4.05

- src/utils/cache/storageCache.ts
- src/utils/cipher.ts
- src/utils/cipherOld.ts
> refactor: cipher

- src/components/Drawer/src/BasicDrawer.vue
- src/components/SimpleMenu/src/components/Menu.vue
- src/components/SimpleMenu/src/components/useMenu.ts
- src/components/SimpleMenu/src/components/useSimpleMenuContext.ts
> chore: fix SimpleRootMenuContextProps type error

- src/layouts/default/header/components/notify/NoticeList.vue
> fix(ATypographyParagraph): type:check error

- src/components/Drawer/src/BasicDrawer.vue
> fix: 修复设置抽屉弹框滚动条样式异常

- src/views/demo/table/FormTable.vue
> fix: checkedKeys use unref bug

- src/design/dark.less
- src/design/index.less
- src/design/theme.less
- src/layouts/default/header/index.less
- src/layouts/default/tabs/index.less
- src/views/demo/comp/modal/Modal4.vue
> fix: 修复黑暗模式下一些样式问题

- src/layouts/default/header/components/notify/NoticeList.vue
> fix: 修复notice样式绑定路径错误

- src/components/Application/src/AppDarkModeToggle.vue
- src/design/color.less
- src/layouts/default/header/components/notify/index.vue
- src/logics/initAppConfig.ts
- src/logics/theme/dark.ts
- src/logics/theme/updateBackground.ts
> perf(darkMode): 优化深色模式颜色切换相关方法; 增加根据主题更新自定义颜色方法和示例

- src/App.vue
- src/components/Table/src/BasicTable.vue
- src/logics/theme/dark.ts
> perf(ConfigProvider): 配置antdv主题色, 使其与modifyVars配置一致

- src/components/Form/src/components/ApiSelect.vue
修复 isFirstLoaded 状态没有重置导致 fetch方法只会调用一次
> fix(ApiSelect.vue ) isFirstLoaded 状态 没有重置导致fetch方法只会调用一次

- src/logics/theme/dark.ts
> fix(dark): fix --text-color light color not work

- src/components/Upload/src/BasicUpload.vue
- src/components/Upload/src/FileList.vue
- src/components/Upload/src/UploadModal.vue
- src/components/Upload/src/props.ts
- src/hooks/web/useSortable.ts
- src/utils/types.ts
> feat(Upload): file list add  drag func

- src/design/var/breakpoint.less
> fix: breakpoint

- src/settings/encryptionSetting.ts
- src/store/plugin/persist.ts
- src/utils/cache/index.ts
- src/utils/cache/storageCache.ts
> feat: pinia persist plugin custom serializer

- src/components/Form/src/hooks/useFormEvents.ts
> fix: validateFields await missing

- src/views/demo/system/dept/dept.data.ts
> fix(dept): no parentDept can edit parentDept

- src/layouts/default/feature/index.vue
- src/layouts/default/tabs/components/SettingButton.vue
- src/layouts/default/tabs/index.vue
> Move setting button to tabs when fold，does not affect full content mode at all.
> feat(layout): move setting button to tabs when fold

- src/components/Upload/src/components/ImageUpload.vue
- src/views/demo/form/index.vue
> perf(ImageUpload): 根据官方示例设置图片回显格式

- src/enums/breakpointEnum.ts
> perf(breakpointEnum): 修改enum与breakpoint.less内一致

- src/components/Icon/src/IconPicker.vue
这个PR主要处理了2个问题：
1. 修复了`FormItem`中使用`IconPicker`导致的外层容器`props`被覆盖的问题（`attrs`透传
2. 优化了操作体验，点击`input`可以直接触发`popover`(配合`placeholder`的提示
> perf(IconPicker): input  trigger popover by click

- src/components/Form/src/BasicForm.vue
> fix(BasicForm): validate Form tip height

- src/views/demo/feat/breadcrumb/ChildrenList.vue
- src/views/demo/feat/breadcrumb/ChildrenListDetail.vue
- src/views/demo/feat/breadcrumb/FlatList.vue
- src/views/demo/feat/breadcrumb/FlatListDetail.vue
- src/views/demo/feat/click-out-side/index.vue
- src/views/demo/feat/context-menu/index.vue
- src/views/demo/feat/copy/index.vue
- src/views/demo/feat/download/index.vue
- src/views/demo/feat/ellipsis/index.vue
- src/views/demo/feat/full-screen/index.vue
- src/views/demo/feat/icon/index.vue
- src/views/demo/feat/img-preview/index.vue
- src/views/demo/feat/menu-params/index.vue
- src/views/demo/feat/msg/index.vue
- src/views/demo/feat/print/index.vue
- src/views/demo/feat/session-timeout/index.vue
- src/views/demo/feat/tab-params/index.vue
- src/views/demo/feat/tabs/TabDetail.vue
- src/views/demo/feat/tabs/index.vue
> refactor: some feat pages transfer setup grammar

- src/components/SimpleMenu/src/components/menu.less
- src/layouts/default/setting/SettingDrawer.tsx
- src/layouts/default/sider/MixSider.vue
> feat(menu):  Added menu mouse move in mode light style

- src/views/form-design/components/VFormDesign/components/ComponentProps.vue
- src/views/form-design/components/VFormDesign/components/FormProps.vue
- src/views/form-design/components/VFormDesign/config/formItemPropsConfig.ts
- src/views/form-design/components/VFormDesign/modules/FormComponentPanel.vue
- src/views/form-design/components/VFormDesign/modules/PropsPanel.vue
> fix: 修复表单设计的右侧属性配置面板中部分表单错乱的问题

- src/views/demo/comp/transition/index.vue
- src/views/demo/page/account/center/index.vue
- src/views/demo/page/account/setting/index.vue
1. 动画组件改为setup语法糖
2. 个人页(个人中心/个人设置)改为setup语法糖
3. /@/ to @/
> refactor(demo): transition and account use setup

- src/utils/http/axios/Axios.ts
- src/views/demo/feat/icon/index.vue
- src/views/demo/feat/menu-params/index.vue
- src/views/form-design/components/VFormDesign/index.vue
- src/views/sys/lock/LockPage.vue
> style: 修复eslint和stylelint

- src/components/Form/src/BasicForm.vue
- src/components/Form/src/components/ApiCascader.vue
- src/components/Upload/src/components/ImageUpload.vue
- src/views/sys/error-log/index.vue
> fix(type): type:check error

- index.html
> ✏️ 仔细看初次加载/刷新点时候，加载图标下面的文字，在即将跳转到时候会向上抖几个像素，强迫症都犯了。
> fix: 修复index.html加载文字偏移的问题

- src/components/Form/src/BasicForm.vue
其他改了`script setup`语法的组件也要看下，先把这个`issues` #3313 修复
> fix(BasicForm): script setup defineExpose

- src/components/Modal/src/components/ModalWrapper.vue
- src/components/Modal/src/index.less
> fix: fullscreen-modal width wrong

- internal/vite-config/package.json
- internal/vite-config/src/plugins/appConfig.ts
- internal/vite-config/src/plugins/index.ts
- pnpm-lock.yaml
> fix: 设置 baseurl 后不生效的问题

- .vscode/extensions.json
- .vscode/settings.json
- internal/vite-config/package.json
- internal/vite-config/src/config/common.ts
- pnpm-lock.yaml
- uno.config.ts
> chore: 更新 unocss 版本及配置

- src/components/Table/src/BasicTable.vue
> fix: ref table

- .eslintignore
- package.json
- pnpm-lock.yaml
> fix: resolve conflicts between eslint and prettier in package.json

- src/views/demo/feat/ellipsis/index.vue
> fix: Failed to resolve component EllipsisText

- src/design/index.less
- src/layouts/default/content/index.vue
> ✏️ 滚动条所属区域貌似不是很合适，被遮挡了。请看看这样调整到内容区域是否合适？
> fix: scrollbar is obscured

- internal/eslint-config/.eslintignore
- internal/stylelint-config/.eslintignore
- internal/vite-config/.eslintignore
> fix: turbo run lint

- src/components/Table/src/hooks/useColumns.ts
> fix: table index column width is not enough

- src/components/Upload/src/components/ImageUpload.vue
- src/components/Upload/src/props.ts
- src/components/Upload/src/types/typing.ts
修正调整后的ImageUpload组件无法正常使用且无法使用单个上传[#3344]
> 调整后的ImageUpload组件无法正常使用且无法使用单个上传[#3344]

- src/views/demo/table/FormTable.vue
> fix: 解决table复选框点击无法勾选状态问题

- src/views/sys/iframe/index.vue
> feat: iframe postmessage

- src/components/Table/src/types/table.ts
> chore(table): typo

- src/components/Form/src/components/FormItem.vue
- src/components/Form/src/props.ts
- src/components/Form/src/types/form.ts
- src/views/demo/table/tableData.tsx
> feat: table搜索表单值发生改变可以触发reload

- src/components/Table/src/hooks/useTableScroll.ts
> fix:table表格宽度自适应，隐藏的列导致宽度增加

- src/components/Table/src/hooks/useTableScroll.ts
- src/layouts/default/footer/index.vue
- src/settings/designSetting.ts
> 修复关于页脚显示状态、全面模式切换的时候，表格高度计算缺失问题。具体效果可以前往/comp/table/treeTable，然后切换页脚显示和全面模式。
> fix: table height calc when fullcontent and footer visible change

- src/hooks/web/useWatermark.ts
水印添加防篡改，删除水印dom或修改水印dom的属性会自动恢复
预览图
> feat(hooks): useWatermark添加水印防篡改功能(#3395)

- src/components/Table/src/components/settings/ColumnSetting.vue
- src/components/Table/src/components/settings/SizeSetting.vue
- src/components/Table/src/types/table.ts
- src/enums/cacheEnum.ts
- src/store/modules/tableSetting.ts
- src/utils/cache/persistent.ts
- types/store.d.ts
> 斗胆重构了列设置组件，功能基本一致，增加状态持久化（以当前路由的 name 为 key）；
> 行高设置组件增加状态持久化（全局）。
> refactor: ColumnSetting and SizeSetting persist

- src/layouts/default/setting/components/SettingFooter.vue
- src/utils/copyTextToClipboard.ts
> fix: navigator.clipboard 兼容问题 #3372

- src/views/demo/table/FormTable.vue
> fix(FormTable): Invert select bug

- src/design/ant/index.less
- src/design/ant/popconfirm.less
> fix:修复气泡确认框的底部按钮换行的问题

- src/design/index.less
- src/views/sys/login/Login.vue
> fix(autofill): 修复深色模式输入框自动填充后样式异常; 修正登录页不恰当全局样式

- src/design/color.less
- src/design/index.less
- src/logics/theme/dark.ts
修改后不在需要在dark.ts内定义颜色数组，仅需在color.less内增加深浅色变量颜色即可
> perf(darkMode): 深色模式颜色定义以及切换方式优化

- src/components/Table/src/hooks/useTableFooter.ts
解决问题 #2166 
在项目中使用表格开启合计行显示后，合计行不能跟着左右滑动。发现是因为antdv的类名不对，但是我没测试出来原因，我这里生成的叫ant-table-body但是最新版的类名是ant-table-content
修改了一下写法 兼容这两种情况
> 滑动表格内容合计行不跟随滑动bug

- src/components/Table/src/components/settings/ColumnSetting.vue
- src/components/Table/src/components/settings/index.vue
> 反馈得知，action 列需要优先最右显示，现修复之；增加开关，默认不启动列设置缓存。
> fix: column setting about action fixed and default not cache

- src/views/demo/feat/request-demo/index.vue
> docs: 错误重试

- src/design/public.less
> style: 优化滚动条深色模式样式

- src/views/hooks/request/refresy-deps.tsx
- src/views/hooks/request/retry.tsx
> docs: useRequest 依赖 Effect 函数案例

- src/components/Modal/src/BasicModal.vue
- src/components/Table/src/hooks/useRowSelection.ts
> modal 有之前 drawer 一样的问题：https://github.com/vbenjs/vue-vben-admin/pull/3421，修复之。
> Fix modal open logic missing

- src/components/Table/src/hooks/useRowSelection.ts
- src/views/demo/table/FormTable.vue
> 修复 demo /comp/table/formTable 的跨页多选操作
> 而且 onSelect、onSelectAll 仅点击 checkbox/radio 有效，点击行无效
> Fix the demo /comp/table/formTable about selection cross pages

- src/hooks/web/usePage.ts
> 允许 go 操作将新 tab 插入到当前 tab 后面，以满足打开新 tab 形式的 新增/修改 交互。
> feat: insert new tab after current tab

- src/views/sys/iframe/index.vue
> fix: double scroll when use iframe inner

- src/components/Table/src/BasicTable.vue
- src/components/Table/src/components/TableHeader.vue
- src/components/Table/src/components/TableSelectionBar.vue
- src/components/Table/src/hooks/useRowSelection.ts
- src/components/Table/src/hooks/useTableHeader.ts
- src/components/Table/src/props.ts
- src/components/Table/src/types/table.ts
- src/locales/lang/en/component.json
- src/locales/lang/zh-CN/component.json
- src/views/demo/table/AuthColumn.vue
- src/views/demo/table/FooterTable.vue
- src/views/demo/table/FormTable.vue
- src/views/demo/table/RefTable.vue
- src/views/demo/table/TreeTable.vue
- src/views/demo/table/UseTable.vue
> 基于 useRowSelection 支持跨分页多选，此时显示多选情况是必要的，所以根据原 /comp/table/formTable 的 demo 页面，新增内置这个多选状态（默认开关为：不显示）。
> Feat: add TableSelectionBar and enable checkbox rowSelection demo

- src/components/Tree/src/BasicTree.vue
- src/components/Tree/src/TreeIcon.ts
- src/components/Tree/src/components/TreeHeader.vue
- src/components/Tree/style/index.less
- src/views/demo/tree/index.vue
> 调整 BasicTree 的样式，修正各种不对齐的问题。
> style: fix basic tree style alignment

- src/components/Form/src/componentMap.ts
- src/components/Form/src/hooks/useComponentRegister.ts
- src/components/Table/src/hooks/useTableForm.ts
- src/components/Table/src/types/table.ts
- src/utils/is.ts
> types(component): 修复 useComponentRegister 方法无法添加自定义的组件，添加时爆类型错误的问题

- src/components/Markdown/src/Markdown.vue
- src/components/Markdown/src/adapter.js
> fix: 浏览器媒体获取兼容

- src/components/SimpleMenu/src/components/SubMenuItem.vue
> 根据反馈：https://github.com/vbenjs/vue-vben-admin/issues/3492
> 排查是到受以下 commit 的影响：
> SHA-1: 841840f866b55d87b65deb41e5b38d2fc9d7231a
> fix: 修复表单按钮的类型定义外部无法修改重置或者提交按钮的文字的问题
> 现修复之
> fix: can`t hover when menu is colappsed

- src/router/guard/index.ts
> 最近一处优化是改变了内容滚动区域，遗漏了 tab 切换滚动回到顶部的调整，现补充修改之。
> fix: scroll back to top when tab switch

- src/components/ContextMenu/src/createContextMenu.ts
> fix: 修复右键菜单当body带滚动条时，Y坐标位置不正确

- src/layouts/default/setting/handler.ts
> fix(layout): 修复切换导航栏模式,分割菜单的状态不同步,导致页面内容区域存在被遮挡的问题

- src/layouts/default/content/index.vue
> fix: content fixed mode

- src/views/dashboard/analysis/components/SalesProductPie.vue
> change salesProductPie.vue's data name to '成交占比'.

- src/components/Table/src/hooks/useRowSelection.ts
- src/components/Table/src/types/table.ts
> 根据反馈 https://github.com/vbenjs/vue-vben-admin/issues/3539
> 修复点击 checkbox/radio 时候跨页选择功能失效问题。
> fix(Table): selection wrong by click input when cross pages

- src/components/Table/src/components/TableFooter.vue
- src/components/Table/src/components/editable/EditableCell.vue
- src/components/Table/src/helper.ts
- src/components/Table/src/hooks/useCustomRow.ts
- src/components/Table/src/hooks/useDataSource.ts
- src/components/Table/src/hooks/useRowSelection.ts
- src/components/Table/src/hooks/useTable.ts
- src/components/Table/src/hooks/useTableExpand.ts
- src/components/Table/src/hooks/useTableFooter.ts
- src/components/Table/src/hooks/useTableScroll.ts
- src/components/Table/src/props.ts
- src/components/Table/src/types/table.ts
> 统一、规范化 rowKey 和 scroll 的类型声明和使用。
> 此前 rowKey 和 scroll 的类型声明分散不一致，应该取自 ant-design-vue。
> 此前 rowKey 的使用不一致，有些地方强行当作 string 使用，并没有处理 function 的情况。
> 从前关于 rowKey，变量命名有歧义，”rowKey“ 有时候指的是 rowKey，有点时候指的是 keyValue，导致逻辑晦涩难懂。
> fix(rowKey&scroll): declear and usage about rowKey and scroll

- src/components/Table/src/hooks/useRowSelection.ts
> fix(Table): getSelectRows return duplicate records

- src/views/demo/page/form/high/PersonTable.vue
> fix: (page>form>high) expose getDataSource close #3529

- src/components/Modal/src/BasicModal.vue
- src/components/Table/src/hooks/useTableScroll.ts
- src/utils/domUtils.ts
- src/views/demo/comp/modal/Modal5.vue
- src/views/demo/comp/modal/index.vue
- src/views/demo/table/RefTable.vue
- src/views/demo/table/ResizeParentHeightTable.vue
- src/views/demo/table/UseTable.vue
> 来自于 https://github.com/vbenjs/vue-vben-admin/issues/3547，发现以下问题：
> 1. modal 没有传递 fullscreen 事件
> 2. table height 计算没有考虑在 modal 内的场景（若使用 wrapRef，考虑 fullscreen 会变得复杂）
> 3. 原 table height 计算逻辑没有注释比较隐晦，需要略微调整和补充说明
> 现修复并实现上述要点，并修复、添加 demo
> fix: table resize wrong in modal

- src/hooks/web/useContentHeight.ts
> fix: substract -> subtract

- .vscode/settings.json
- src/locales/lang/en.ts
- src/locales/lang/zh_CN.ts
> chore(i18n): add ts,js file support

- apps/test-server/package.json
> fix(test-server): test-server can not lanuch

- src/components/Table/src/hooks/useColumns.ts
> 根据反馈 https://github.com/vbenjs/vue-vben-admin/issues/3559 可以优化支持深度筛选 defaultHidden 设置，原逻辑只筛选首层 columns
> fix(useColumns): handle deep colunm hidden

- src/layouts/default/tabs/index.less
> 根据 https://github.com/vbenjs/vue-vben-admin/issues/3557 微调 tab 的关闭按钮位置。
> fix(tabs): tab close button position

- src/components/Container/src/ScrollContainer.vue
> 根据 https://github.com/vbenjs/vue-vben-admin/issues/3563 确实存在提到的问题2，看提交记录一直存在以下样式锁死：
> src\components\Container\src\ScrollContainer.vue
```
.scroll-container {
width: 100%;
height: 100%;
.scrollbar__wrap {
margin-bottom: 18px !important;
overflow-x: hidden; // 这里锁死了横向滚动的可能性
}
.scrollbar__view {
box-sizing: border-box;
}
}
```
> 请问管理员，这里最初的用意是？注释掉，做 demo 里没发现问题。
- [x I have performed a self-review of my own code
> fix(ScrollContainer): enable x scroll

- src/components/Page/src/PageWrapper.vue
- src/views/demo/page/desc/high/index.vue
修复 PageWrapper headerSticky模式 表现异常问题
before:
after:
> fix(PageWrapper): 修复headerSticky样式

- README.md
> docs: i18n

- src/layouts/default/content/index.vue
- src/layouts/default/feature/index.vue
> 根据 https://github.com/vbenjs/vue-vben-admin/issues/3580 反馈，修复 BackTup 功能。
> fix(BackTop): repair BackTup comp

- src/components/Button/src/PopConfirmButton.vue
> fix: 当TableAction的actions属性中的ActionItem传递了color属性时，PopConfirm的指示箭头颜色异常问题

- src/components/Cropper/src/CropperModal.vue
> 根据 https://github.com/vbenjs/vue-vben-admin/issues/3594 调整 beforeUpload 返回值
> fix(CropperModal): beforeUpload should return false

- src/components/Table/src/components/TableAction.vue
> fix: TableAction设置icon显示iconify关键字

- src/views/sys/exception/Exception.vue
> 关于 https://github.com/vbenjs/vue-vben-admin/issues/3604 提高兼容性（如果开发者想使用 antv 默认的 status 样式）
> refactor(Exception): support original status values with not overrided

- apps/test-server/service/FileService.ts
> fix: fileservice class name

- src/layouts/default/sider/LayoutSider.vue
> 来自于 -> https://github.com/vbenjs/vue-vben-admin/issues/3605
> 针对场景：菜单折叠按钮为“底部”时：
> 关于 breakpoint，
> 组件定义的是 lg: '992px'，
> 而 vben 定义的是 lg: '960px'，
> 现把组件的 breakpoint 设为 md，
> 则组件的 md: '768px' < vben的 lg: '960px'，
> 防止 collapsedWidth 在 960px ~ 992px 之间错误设置为 0，
> 从而防止出现浮动的 trigger（点击无效：breakpoint事件失效）
浮动的 trigger（点击无效：breakpoint事件失效）:
- [xIs the git submission information standard?
- [xMy code follows the style guidelines of this project
- [xI have performed a self-review of my own code
- [xI have commented my code, particularly in hard-to-understand areas
> Fix layout breakpoint

- src/components/Form/src/components/FormItem.vue
> fix about https://github.com/vbenjs/vue-vben-admin/issues/3633，不同组件与 CropperAvatar 的 size 类型冲突
> fix(CropperAvatar): wrong type about the prop size

- src/layouts/default/header/components/user-dropdown/DropMenuItem.vue
> fix(layout): fix warning "Invalid prop name: key is a reserved property"

- src/router/guard/permissionGuard.ts
> fix(router): resolve the next function being called twice

- src/components/EllipsisText/src/Tooltip.vue
- vite.config.ts
> fix: fix ellipsis tooltip bug & 项目启动优化

- src/components/VxeTable/index.ts
…being able to be used
closed #3614
> fix(component): resolve the issue of "vxe-table" export function not being able to be used

- src/components/VxeTable/src/methods.ts
> fix(component): insertNextAt is not a function (#3656)

- src/locales/lang/en/component.json
- src/locales/lang/en/layout.json
> fix: typo in locale

- src/router/helper/menuHelper.ts
- src/router/menus/index.ts
- src/router/types.ts
> fix(router): resolve menu loading failure when permission is in "role mode"

- src/components/Container/src/collapse/CollapseContainer.vue
- src/components/Container/src/collapse/CollapseHeader.vue
- src/components/Description/src/Description.vue
- src/views/demo/comp/qrcode/index.vue
- src/views/demo/page/account/center/index.vue
- src/views/demo/page/account/setting/AccountBind.vue
- src/views/demo/page/account/setting/BaseSetting.vue
- src/views/demo/page/account/setting/MsgNotify.vue
- src/views/demo/page/account/setting/SecureSetting.vue
> fix: typo in Container

- src/components/Form/src/components/ApiSelect.vue
- [x ] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the …
> 修改ApiSelect的isFirstLoaded赋值逻辑，只有当加载报错时才需要恢复未初次加载状态

- src/components/SimpleMenu/src/SimpleSubMenu.vue
- src/router/helper/menuHelper.ts
> Pref: 路由菜单取title字段 而不是name，树结构数据修改

- index.html
> fix: remove duplicate code

- src/enums/appEnum.ts
> fix: Correct spelling error in comments

- src/components/Form/src/hooks/useFormEvents.ts
- src/components/Form/src/hooks/useFormValues.ts
- src/components/VxeTable/src/components/common.tsx
- src/components/VxeTable/src/const.ts
- src/components/VxeTable/src/helper.ts
> feat(input): add auto-trimming for vxe-table input components

- src/components/VirtualScroll/src/VirtualScroll.vue
- src/design/ant/input.less
- src/views/demo/comp/scroll/VirtualScroll.vue
> feat(VirtualScroll): 虚拟滚动增加滚动到顶部, 底部, 指定项方法, 并增加demo按钮

- src/components/Application/src/search/useMenuSearch.ts
> fix: 菜单搜索功能修复

- src/components/Form/src/hooks/useFormEvents.ts
> fix: bug RangePicker with componentProps valueFormat ('YYYY-MM-DD') does not return the formatted value when using form validate() method. #3690

- src/components/Table/src/components/HeaderCell.vue
> style(BasicTable): 表头帮助图标 多余颜色样式去除, 修复深色图标看不清问题

- src/components/Menu/src/components/MenuItemContent.vue
- src/layouts/default/header/components/Breadcrumb.vue
> fix(menu): top menu and breadcrumb show wrong

- src/components/Upload/src/components/ImageUpload.vue
1.修正ImageUpload直接使用时无法正常回传value
2.修正ImageUpload无法正常初始化第一次传值
> fix: 1.修正ImageUpload直接使用时无法正常回传value 2.修正ImageUpload无法正常初始化第一次传值

- src/components/Modal/src/index.less
> fix(BasicModal): 修复BasicModal跟原生Modal样式冲突问题

- .vscode/extensions.json
- .vscode/settings.json
- src/directives/permission.ts
- types/directives.d.ts
-  Complete dirctives types
- Special color identification of permission instructions
> types: complete dirctives and v-role custom color 

- src/components/Page/src/PageWrapper.vue
- src/components/Table/src/BasicTable.vue
修复在具有“fixedHeight”和“contentFullHeight"的“PageWrapper”，以及在此基础上“BasicTable”的“canResize”设为true时，使用标签页右侧"全屏内容按钮"或项目设置中的“全屏内容”时高度错乱
> fix(component): resovle fullscreen content issues with "fixedHeight" and "contentFullHeight" combined

- package.json
- pnpm-lock.yaml
- vite.config.ts
1、Open web page in chrome
2、Press Ctrl(^)+Shift(⇧) open Inspector
3、select DOM and click
4、Auto open Vscode code line
5、Press Ctrl(^)+Shift(⇧) off Inspector
> chore: add Inspector(developer open vscode)

- src/hooks/web/useWatermark.ts
> perf: 优化水印在控制台可以hide的问题

- src/components/Modal/src/index.less
修复“createMessage”的样式错乱位置，关联的PR：
[https://github.com/vbenjs/vue-vben-admin/pull/3720](url)
- [] I have made corresponding changes to the documentation
- [] New and existing unit tests pass locally with my changes
- [] Any dependent changes have been merged and published in downstream modules
> fix: 修复确认弹出框样式错乱的问题

- src/components/Upload/src/components/UploadModal.vue
> fix: 修复文件上传过程中删除文件终止上传时，上传状态未改变不能关闭Modal的bug

- src/utils/http/axios/index.ts
修复当 http 状态码为 **401** 时仍然发出重试请求（如果有设置`retryRequest.isOpenRetry: true`）
- [] I have made corresponding changes to the documentation
> fix(util): resolve executing retry even when HTTP status code is 401

- src/components/Upload/src/components/ImageUpload.vue
- src/components/Upload/src/helper.ts
> fix: 修正图片上传组件允许自定义上传格式限制

- src/components/Form/src/hooks/useFormEvents.ts
- src/views/demo/form/AppendForm.vue
-  1.修复不能通过form组件的 setFieldsValue和modal 进行表单组赋值的问题
-  2.添加增删表单组的示例，可以一组组添加并且增删与赋值（之前`表单增删示例`的demo重命名成表单项了，因为从源码看这里本质是一项项添加的）
> fix(batch-add-formitem):fix the form not working when setFieldsValue through form-groups and add a demo with form groups

- package.json
- pnpm-lock.yaml
- src/views/demo/steps/index.vue
> feat(demo): use Tour component replace dirverjs

- .github/ISSUE_TEMPLATE/1-bug.md
- .github/ISSUE_TEMPLATE/3-bug-cn.md
project's monorepo is organized using pnpm workspace, it cannot be run with npm or yarn
> docs(github): update doc

- Dockerfile
node version 18 is required for pnpm.
> update node version of dockerfile

- src/components/Upload/src/components/ImageUpload.vue
fix https://github.com/vbenjs/vue-vben-admin/issues/3797
> fix(imgupload): resultField causing with error display && setField uncertain

- src/router/routes/modules/demo/flow.ts
- src/router/routes/modules/demo/level.ts
修改了两个路由配置文件里的命名，没有和文件名对应，虽然不影响功能
> fix: Rename the default export name

- README.md
- README.zh-CN.md
> Update git url

- src/components/Loading/src/createLoading.ts
- src/components/Loading/src/useLoading.ts
- src/directives/loading.ts
> fix(Loading): 处理v-loading指令和useLoading的内存泄露

- src/views/demo/form/RuleForm.vue
fix https://github.com/vbenjs/vue-vben-admin/issues/3854
> fix(form->demo): unset date value

- src/components/Loading/src/createLoading.ts
Hot fix the revision bcd98ee0672047aafebdd504ef0ecc630b5068da
Issue: [3876](https://github.com/vbenjs/vue-vben-admin/issues/3876)
Reference:  https://github.com/vbenjs/vue-vben-admin/commit/bcd98ee0672047aafebdd504ef0ecc630b5068da#commitcomment-142415303
> fix(loading): useLoading is not working as expected

- src/components/Application/src/search/AppSearchModal.vue
- src/components/Application/src/search/useMenuSearch.ts
- src/components/Table/src/hooks/useDataSource.ts
Highlight match chars when search menu.
Sort the list by match chars: full match > partial match > localeCompare
> perf(menu search): highlight match chars when search menu

- src/views/demo/feat/screenshot/index.vue
---
此`pr`主要是对截图模块的优化及扩展，主要改动为：
- 截图示例模块的布局微调、优化部分代码
- 新增`打印截图`，`下载截图`功能
打印截图功能的需求会出现在G端(政府端)业务上，比如行政通知单、执法单、报告单等，这里的`打印截图`功能可以满足粗粒度的打印功能
现在，截图模块是这样的：
> perf(screenshot): optimize the screenshot code && add print and download

- src/components/Loading/src/createLoading.ts
- src/components/Loading/src/useLoading.ts
- src/directives/loading.ts
> fix: destroy方法命名修正

- src/router/guard/permissionGuard.ts
修改前：
http://localhost:5173/#/dashboard/analysis?tab=1  ->  http://localhost:5173/#/login?redirect=/dashboard/analysis
修改后：
http://localhost:5173/#/dashboard/analysis?tab=1  ->  http://localhost:5173/#/login?redirect=/dashboard/analysis?tab=1
即保留所有参数，确保用户登录后进入正确的路由
> perf: 未登录重定向路径存储改为完整路径

- src/utils/http/axios/axiosRetry.ts
> fix: axios retry losing headers

- src/components/Upload/src/components/UploadPreviewModal.vue
fix:https://github.com/vbenjs/vue-vben-admin/issues/3906
> perf(UploadPreviewModal): delete invalid assign

- internal/vite-config/src/config/application.ts
Reference issue: https://github.com/vbenjs/vue-vben-admin/issues/3905
In revision: https://github.com/vbenjs/vue-vben-admin/commit/a6086f4cc8f33fea7431f3d39eb73dda20c325bd
_(EDITED)_ 
Using `entryFileNames: 'index.js'` in Vite is generally not recommended due to several issues: 
1. **Debugging Difficulty**: Identical filenames make debugging harder as they don't reflect their origin or purpose.
Advantages of using  `[name]-[hash]`
1. Clarity: Each output file retains a clear connection to its entry file, making it easier to identify what each file corresponds to.
2. Consistency: This naming convention is more consistent if you have many files, as each file keeps its original name with a hash appended, making the build output more organized and predictable.
Also in Dockerfile it uses …
> fix: improve build file naming convention and caching

- src/components/VxeTable/src/css/index.scss
fix: vxe-table index.css已废弃，切换至all
> fix: vxe-table index.css已废弃，切换至all

- package.json
- pnpm-lock.yaml
- src/components/VxeTable/src/components/AApiSelect.tsx
- src/components/VxeTable/src/components/AApiTreeSelect.tsx
- src/components/VxeTable/src/components/AAutoComplete.tsx
- src/components/VxeTable/src/components/AButton.tsx
- src/components/VxeTable/src/components/AButtonGroup.tsx
- src/components/VxeTable/src/components/ACascader.tsx
- src/components/VxeTable/src/components/ACheckboxGroup.tsx
- src/components/VxeTable/src/components/ADatePicker.tsx
- src/components/VxeTable/src/components/AEmpty.tsx
- src/components/VxeTable/src/components/AInput.tsx
- src/components/VxeTable/src/components/AInputNumber.tsx
- src/components/VxeTable/src/components/AInputSearch.tsx
- src/components/VxeTable/src/components/AMonthPicker.tsx
- src/components/VxeTable/src/components/ARadioGroup.tsx
- src/components/VxeTable/src/components/ARangePicker.tsx
- src/components/VxeTable/src/components/ARate.tsx
- src/components/VxeTable/src/components/ASelect.tsx
- src/components/VxeTable/src/components/ASwitch.tsx
- src/components/VxeTable/src/components/ATimePicker.tsx
- src/components/VxeTable/src/components/ATreeSelect.tsx
- src/components/VxeTable/src/components/AWeekPicker.tsx
- src/components/VxeTable/src/components/AYearPicker.tsx
- src/components/VxeTable/src/components/common.tsx
- src/components/VxeTable/src/components/index.tsx
- src/components/VxeTable/src/css/index.scss
- src/components/registerGlobComp.ts
> fix(VxeTable): 更新vxe-table以及相关依赖,修改废弃API至最新

- src/components/SimpleMenu/src/components/MenuItem.vue
- src/components/SimpleMenu/src/components/SubMenuItem.vue
- src/components/SimpleMenu/src/components/useSimpleMenuContext.ts
> fix: typo opend -> opened

- src/logics/initAppConfig.ts
- [x ] I have commented my code, particularly in hard-to-understand areas
> types(logic): 减少冗沉，用了泛型

- src/components/Table/src/components/editable/EditableCell.vue
> perf(component): 优化EditableCell组件handleSubmit方法报错时增加warn日志显示

- src/components/Preview/src/functional.ts
> perf(Preview): 优化实例创建更新逻辑, 防止重复创建dom

- src/components/Upload/src/components/UploadModal.vue
[#3958](https://github.com/vbenjs/vue-vben-admin/issues/3958)
修复上传以后无法删除的问题
> fix(upload): 修复上传组件删除无效bug

- src/layouts/default/header/components/UpgradePrompt.vue
- src/locales/lang/en/layout.json
- src/locales/lang/zh-CN/layout.json
> chore: update UpgradePrompt

- .github/workflows/codeql.yml
- .github/workflows/draft.yml
- package.json
> feat(ci): add codeql.yml [deploy]

- internal/vite-config/src/config/application.ts
> fix: 修复文档链接错误

- README.zh-CN.md
- packages/effects/layouts/src/widgets/preferences/blocks/layout/content.vue
> fix: correct i18n translation

- packages/effects/chart-ui/src/echarts/use-echarts.ts
修复了设置内容为定宽或流式，echarts未resize的问题
> fix: Adjusted contentCompact without triggering ECharts resize

- src/components/Form/src/components/ApiSelect.vue
- src/views/demo/form/index.vue
feat: 1.ApiSelect增加远程搜索功能 2.ApiSelect设定懒加载时允许控制空搜索时不查询 3.增加下拉远程搜索Json版本demo
> feat: 1.ApiSelect增加远程搜索功能 2.ApiSelect设定懒加载时允许控制空搜索时不查询 3.增加下拉远程搜索Json版本demo

- src/logics/initAppConfig.ts
- src/router/helper/menuHelper.ts
- src/router/menus/index.ts
- src/store/modules/permission.ts
> 删除了多余的菜单数据的步骤，减少性能开销，优化初始化速度。

- .vscode/launch.json
> feat: add debugger type

- docs/src/guide/essentials/settings.md
- packages/@core/base/icons/src/lucide.ts
- packages/@core/base/typings/src/app.d.ts
- packages/@core/preferences/src/config.ts
- packages/@core/preferences/src/types.ts
- packages/effects/layouts/src/basic/header/header.vue
- packages/effects/layouts/src/basic/layout.vue
- packages/effects/layouts/src/widgets/preferences/blocks/layout/tabbar.vue
- packages/effects/layouts/src/widgets/preferences/blocks/layout/widget.vue
- packages/effects/layouts/src/widgets/preferences/index.ts
- packages/effects/layouts/src/widgets/preferences/preferences-button.vue
- packages/effects/layouts/src/widgets/preferences/preferences-sheet.vue
- packages/effects/layouts/src/widgets/preferences/preferences.vue
- packages/locales/src/langs/en-US.json
- packages/locales/src/langs/zh-CN.json
> feat: supports specifying the position of the preference button

- .github/release-drafter.yml
- packages/@core/base/icons/src/lucide.ts
- packages/@core/ui-kit/tabs-ui/src/components/tabs-chrome/tabs.vue
- packages/@core/ui-kit/tabs-ui/src/components/tabs/tabs.vue
- packages/@core/ui-kit/tabs-ui/src/tabs-view.vue
- packages/@core/ui-kit/tabs-ui/src/use-tabs-view-scroll.ts
- packages/effects/layouts/package.json
- packages/effects/layouts/src/basic/tabbar/tabbar.vue
- pnpm-lock.yaml
> perf: improve tabs-view scrolling

- .vscode/settings.json
> chore: update vscode settings.json

- docs/src/en/guide/essentials/settings.md
- docs/src/guide/essentials/settings.md
- packages/@core/base/typings/src/app.d.ts
- packages/@core/preferences/src/config.ts
- packages/@core/preferences/src/use-preferences.ts
- packages/effects/layouts/src/basic/header/header.vue
- packages/effects/layouts/src/basic/layout.vue
- packages/effects/layouts/src/widgets/global-search/global-search.vue
- packages/effects/layouts/src/widgets/preferences/blocks/layout/widget.vue
- packages/locales/src/langs/en-US.json
- packages/locales/src/langs/zh-CN.json
> feat: preference button supports automatic positioning

- .lintstagedrc.mjs
- apps/web-antd/.env.production
- apps/web-ele/.env.production
- apps/web-naive/.env.production
- docs/.vitepress/config/shared.mts
- docs/package.json
- docs/src/components/common-ui/vben-drawer.md
- docs/src/components/common-ui/vben-modal.md
- docs/src/en/guide/essentials/settings.md
- docs/src/guide/essentials/settings.md
- internal/lint-configs/eslint-config/src/configs/perfectionist.ts
- internal/tailwind-config/src/index.ts
- internal/vite-config/package.json
- internal/vite-config/src/config/application.ts
- internal/vite-config/src/plugins/archiver.ts
- internal/vite-config/src/plugins/index.ts
- internal/vite-config/src/typing.ts
- internal/vite-config/src/utils/env.ts
- playground/.env.production
- pnpm-lock.yaml
- turbo.json
> feat: add archive plug-in to output dist.zip after build

- src/utils/index.ts
> Support array parameter parsing

- packages/effects/common-ui/src/components/captcha/point-selection-captcha.vue
> fix: module is not listed in package. json dependencies

- internal/vite-config/package.json
- packages/locales/package.json
- playground/src/router/routes/modules/demos.ts
- pnpm-lock.yaml
> chore: bump vue-i18n from 9.14.0 to 10.0.1

- src/components/Table/src/components/settings/index.vue
> fix: 修复table setting 上下不居中

- packages/@core/ui-kit/popup-ui/src/drawer/drawer.vue
- packages/@core/ui-kit/shadcn-ui/src/components/ui/sheet/SheetOverlay.vue
> fix: when modal and drawer exist at the same time, click Close All

- src/components/Table/src/hooks/useRowSelection.ts
> fix(table): Fixed table tree structure bug

- packages/@core/ui-kit/popup-ui/src/drawer/drawer.vue
- packages/@core/ui-kit/popup-ui/src/modal/modal.vue
- packages/@core/ui-kit/shadcn-ui/src/components/ui/dialog/DialogOverlay.vue
- packages/@core/ui-kit/shadcn-ui/src/components/ui/sheet/SheetOverlay.vue
> fix: when multiple pop-ups exist at the same time, clicking will close all

- docs/src/en/guide/essentials/development.md
- docs/src/guide/essentials/development.md
- package.json
- scripts/turbo-run/src/run.ts
- turbo.json
> fix: try to fix the error reported by the stub command in the window system

- apps/web-ele/src/views/demos/element/index.vue
- apps/web-naive/src/adapter/form.ts
- docs/src/demos/vben-form/query/index.vue
- packages/@core/ui-kit/form-ui/src/components/form-actions.vue
- packages/@core/ui-kit/form-ui/src/types.ts
- packages/effects/plugins/src/vxe-table/use-vxe-grid.vue
- playground/src/views/examples/form/merge.vue
- playground/src/views/examples/form/query.vue
> refactor: change the form button field from text to content to prevent conflicts with the frame

- internal/node-utils/package.json
- internal/node-utils/src/index.ts
- package.json
- packages/effects/plugins/src/vxe-table/init.ts
- packages/effects/plugins/src/vxe-table/theme.css
- packages/effects/plugins/src/vxe-table/use-vxe-grid.vue
- playground/src/views/examples/vxe-table/remote.vue
- pnpm-lock.yaml
- pnpm-workspace.yaml
close #4639 
close #4593
close #4624
> chore: add vxe-table toolbar example

- scripts/deploy/Dockerfile
> fix: docker image build failed

- packages/effects/layouts/package.json
- packages/effects/layouts/src/basic/layout.vue
- pnpm-lock.yaml
- pnpm-workspace.yaml
> fix: unable to preventDefault inside passive event listener invocation

- docs/.vitepress/config/en.mts
- docs/.vitepress/config/zh.mts
- packages/effects/plugins/src/vxe-table/style.css
- packages/effects/plugins/src/vxe-table/use-vxe-grid.vue
> fix: correct grid styling issue

- packages/@core/ui-kit/form-ui/src/form-render/form-field.vue
> fix: resolve onChange issue in form component

- internal/lint-configs/eslint-config/src/configs/unicorn.ts
- package.json
- packages/@core/ui-kit/form-ui/src/form-render/form-field.vue
- pnpm-lock.yaml
- pnpm-workspace.yaml
> fix: resolve issue with Upload component not working correctly inside Form

- playground/src/views/examples/vxe-table/basic.vue
> chore: remove redundant test code

- packages/effects/common-ui/src/components/page/page.vue
修复在表格已设置自动调整高度时，偶发性地出现高度计算错误的问题。
fix #5035
fix #5015
> fix: table auto height

- packages/effects/plugins/src/vxe-table/init.ts
修复表单的字段配置按钮点击后报错的问题。
fix: #5106
> fix: resolve table toolbar error

- docs/src/components/common-ui/vben-form.md
- packages/@core/ui-kit/form-ui/src/form-api.ts
- packages/@core/ui-kit/form-ui/src/types.ts
增强fieldMappingTime，允许自定义格式化函数。
close #5381
> perf: improve fieldMappingTime to support format function

- apps/web-antd/src/router/routes/modules/dashboard.ts
- apps/web-ele/src/router/routes/modules/dashboard.ts
- apps/web-naive/src/router/routes/modules/dashboard.ts
> fix: demos route fixed

- packages/@core/ui-kit/form-ui/src/form-api.ts
> fix: form update state error before form mounted

- apps/backend-mock/utils/mock-data.ts
修复后端权限模式下，退出并重新登陆时路由报错的问题
fix #5463
> fix: menu data for backend mode fixed

- apps/web-antd/src/bootstrap.ts
- apps/web-ele/src/bootstrap.ts
- apps/web-naive/src/bootstrap.ts
- packages/effects/plugins/package.json
- packages/effects/plugins/src/motion/index.ts
- packages/effects/plugins/src/motion/types.ts
- playground/src/api/request.ts
- playground/src/bootstrap.ts
- playground/src/views/examples/motion/index.vue
- pnpm-lock.yaml
- pnpm-workspace.yaml
> feat: demo of motion plugin

- packages/effects/common-ui/src/components/count-to/count-to.vue
- packages/effects/common-ui/src/components/count-to/index.ts
- packages/effects/common-ui/src/components/count-to/types.ts
- packages/effects/common-ui/src/components/index.ts
- playground/src/router/routes/modules/examples.ts
- playground/src/views/examples/count-to/index.vue
重构CountTo数字动画组件。出于向下兼容的原因，之前的VbenCountToAnimator组件仍然保留
> refactor: new `CountTo` component with demo

- playground/src/router/routes/modules/demos.ts
修复演示的嵌套菜单path配置导致的面包屑跳转问题
fix: #5664
> fix: demo nested menu path

- docs/src/components/common-ui/vben-api-component.md
> docs: fix api-component demo link

- packages/@core/ui-kit/shadcn-ui/src/components/button/check-button-group.vue
> fix: possible circular reference issue during build

- packages/stores/src/modules/tabbar.ts
解决 https://github.com/vbenjs/vue-vben-admin/issues/6242 的问题
原代码`tab.key`获取为空  导致当前tab也被加入需要关闭的list中 造成问题
使用封装的方法进行兜底处理
> fix: tab cannot be displayed correctly after browser refresh

- packages/effects/common-ui/src/components/page/page.vue
Reverts vbenjs/vue-vben-admin#6422
fixed: #6472
> revert: page height revert #6422
