package.json
src/components/Excel/index.ts
src/components/Excel/src/Export2Excel.ts
src/components/Excel/src/ExportExcelModel.vue
src/components/Excel/src/ImportExcel.tsx
src/components/Excel/src/types.ts
src/router/menus/modules/demo/comp.ts
src/router/routes/modules/demo/comp.ts
src/views/demo/comp/excel/ExportToExcel.vue
src/views/demo/comp/excel/ImportExcel.vue
src/views/demo/comp/excel/data.ts
yarn.lock

feat(excel): add import/export

---

src/layouts/default/LayoutBreadcrumb.tsx
src/layouts/default/LayoutHeader.tsx
src/layouts/default/setting/SettingDrawer.tsx
src/settings/projectSetting.ts
src/types/config.d.ts

feat(breadcrumb): support showIcon

---

mock/demo/account.ts
src/api/demo/account.ts
src/api/demo/model/accountModel.ts
src/router/menus/modules/demo/page.ts
src/router/routes/modules/demo/page.ts
src/views/demo/page/account/setting/AccountBind.vue
src/views/demo/page/account/setting/BaseSetting.vue
src/views/demo/page/account/setting/MsgNotify.vue
src/views/demo/page/account/setting/SecureSetting.vue
src/views/demo/page/account/setting/data.ts
src/views/demo/page/account/setting/index.vue

feat: add accountSetting page

---

src/components/Table/src/components/editable/EditableCell.vue

这个地方应该返回真实值，而不是editValueMap处理后的值或Select插槽的option.label。

修正单元格编辑提交时的返回值

---

src/components/Table/src/BasicTable.vue

fix(style): add table title min-height

---

src/components/Modal/src/BasicModal.vue

修复BasicModal组件的okButtonProps、cancelButtonProps属性与Ant design Modal组件的定义差别所引起的warn。

fix(modal): proptype conflict with ant design modal(fixed: #545)

---

src/components/Qrcode/src/index.vue
src/components/Qrcode/src/types.ts
src/views/demo/comp/qrcode/index.vue

修改QRcode组件的done事件的参数，传入画板的绘制上下文对象以便可以方便地对QRcode组件的二维码进行二次加工，比如绘制提示文字等等。在组件的示例页面增加了新的自定义绘制的例子。

feat(qrcode): custom drawing support

---

src/components/Tree/src/index.vue
src/components/Tree/src/props.ts
src/components/Tree/src/types.ts

当tree处于抽屉或者对话框中时，右键菜单会因为z-index太低而没能显示在对话框或抽屉的上层。
此PR修改了对beforeRightClick的回调的处理，允许beforeRightClick返回菜单的items数组（兼容之前的代码写法）或者返回ContextMenuOptions来对右键菜单进行更多定制，比如返回{styles:{"z-index":2010},items}来让右键菜单可以在抽屉或弹窗中正确显示。

perf(tree): 改进beforeRightClick回调支持对菜单进行更多配置

---

src/components/Tree/src/props.ts

当Tree启用checkable、checkStrictly属性时，checkedKeys的值是一个Object而不是Array。

fix(tree): value prop type

---

src/components/Form/src/components/FormItem.vue
src/components/Tree/src/index.vue

1. 改进FormSchema的required属性，使之支持多选select、tree等值类型为数组的组件校验；
2. 修复basicTree组件的以下问题：
- onCheck中抛出update:value和change事件的顺序不正确导致tree组件的change事件中获取的值为尚未更新的旧值从而没有使用正确的值来校验
- setCheckedKeys、checkAll 函数没有触发change事件从而导致tree不会自动校验

修复和改进一些小问题

---

build/vite/plugin/theme.ts

修复非默认颜色主题时，RadioButtonGroup的checked状态的按钮文字颜色被覆盖为与背景相同颜色的问题。

fix(theme):  wrong color when RadioButtonGroup checked

---

src/views/sys/login/LoginForm.vue

登录页面的回车事件绑定不正确，导致可能会意外提交登录表单：想按按下Enter关闭错误Modal时、在注册表单或其它表单按下Enter时等等。现已将Enter事件绑定在登录Form上

fix(login): incorrect enter event bind

---

src/components/Tree/src/index.vue
src/components/Tree/src/types.ts
src/views/demo/tree/index.vue

修复Tree的onCheck事件缺少节点参数的问题。fixed: #315

fix(tree): onCheck event lose origin param. fixed: #315

---

mock/sys/user.ts
src/api/sys/model/userModel.ts
src/layouts/default/header/components/lock/LockModal.vue
src/layouts/default/header/components/user-dropdown/index.vue
src/views/dashboard/workbench/components/WorkbenchHeader.vue
src/views/demo/page/account/center/index.vue
src/views/demo/page/account/setting/BaseSetting.vue
src/views/sys/lock/LockPage.vue
types/store.ts

在显示头像的地方正确显示当前登录用户的头像而不是固定的图片，已补充mock接口返回的avatar字段。

fix(avatar): show current user's avatar

---

src/components/Form/src/BasicForm.vue
src/components/Form/src/componentMap.ts
src/components/Form/src/props.ts
src/components/Form/src/types/form.ts
src/components/Form/src/types/index.ts
src/views/demo/form/index.vue

1.添加Form布局方式,当layout: 'vertical',labelWidth可以控制col间距
2.添加Form的全局label对齐方式, labelAlign: left | right
3.添加Form的Row组件所支持属性,控制Col间的间距,对齐方式,布局方式

feat(form):  add 'layout', 'labelAlign', 'rowProps' option

---

mock/_util.ts
mock/sys/menu.ts
mock/sys/user.ts
src/api/sys/menu.ts
src/api/sys/model/menuModel.ts
src/api/sys/model/userModel.ts
src/api/sys/user.ts
src/hooks/web/usePermission.ts
src/store/modules/permission.ts
src/store/modules/user.ts
src/views/demo/permission/back/Btn.vue
src/views/demo/permission/back/index.vue

移除getUserInfo、getPermCode、getMenuList接口的userId参数。
这些接口应当始终与当前登录用户相关而无需传递userId。
请在vite-plugin-mock合并了https://github.com/anncwb/vite-plugin-mock/pull/23 之后，再合并本PR。本PR相关功能依赖mock数据中的request headers

refactor(api): remove unnecessary userId param

---

src/store/modules/permission.ts
src/views/sys/login/SessionTimeoutLogin.vue

修复超时重新登录的页面在某些逻辑下未能正确刷新数据的问题。
1、后台权限模式下，如果在token失效或过期之后直接手动F5刷新页面，会在请求菜单数据时收到接口应答要求重新登陆，此时如果载入了session timeout login组件的话，登录成功后没能重新请求菜单数据。
2、无论何种权限模式下，session timeout login组件在登陆成功后，假如登录的并非之前的用户，应当刷新页面丢弃就用户的页面状态

fix: session timeout login logic error

---

src/locales/setupI18n.ts
src/locales/useLocale.ts

修复首次加载或改变语言导致重载时，不会设置 `HTML` 的 `lang` 属性

fix: Fix the problem that the `lang` attribute of `HTML` will not be set when it is first loaded

---

src/components/Tinymce/src/Editor.vue
src/components/Tinymce/src/ImgUpload.vue

fix(Tinymce):  Read only status upload button can also be used

---

src/components/Page/src/PageWrapper.vue
src/layouts/default/content/useContentViewHeight.ts
src/layouts/default/footer/index.vue
src/layouts/default/header/MultipleHeader.vue

当开启`页脚`时，使用`PageWrapper`的`contentFullHeight`功能，实际计算高度未减去页脚高度。
需要滑动才得以看到页脚。
第一次开启时，页面将计算两次height，未测试 `fixedHeight: true`的情况，看源码想必是没有问题的。

fix(useViewHeight): 修复useContentViewHeight未计算 页脚 的问题。

---

mock/demo/select-demo.ts
src/api/demo/model/optionsModel.ts
src/api/demo/select.ts
src/components/Form/src/components/ApiSelect.vue
src/views/demo/form/index.vue

fix(ApiSelect demo): add demo about ApiSelect's use

---

CHANGELOG.zh_CN.md
src/components/Page/src/PageWrapper.vue
src/layouts/default/footer/index.vue

perf(PageWrapper): 优化PageWrapper在page的footer与全局页脚同时开启时的高度计算表现。
contentHeight 未计算 全局footer 高度，开启PageWrapper的footer时会全局遮挡
1. 高度计算时，如果全局footer开启，需要减去全局footer
2. 取消padding-bottom
> 当前尚未解决被PageWrapper的footer直接遮挡 全局footer 的问题。  PageWrapper的footer是浮动状态。

perf(PageWrapper): 优化PageWrapper在page的footer与全局页脚同时开启时的高度计算表现。

---

src/components/Page/src/PageWrapper.vue
src/components/Page/src/types.ts
src/components/Page/src/useContentHeight.ts
src/layouts/default/content/useContentViewHeight.ts

> perf(pagewrapper): 优化PageWrapper的高度自适应表现，适应外层包装dom的情况。
使用 getViewportOffset 的 bottomIncludeBody 代替 useContentViewHeight
基于`PageWapper`的顶端到底端距离进行计算（与BasicTable使用同样的方案）
可适应`PageWrapper`外层包装dom且添加`padding`/`margin`的情况，同时修复了`page's footer`与`layout's footer`同时开启时的错误情况。

perf(pagewrapper): 优化PageWrapper的高度自适应表现，适应外层包装dom的情况。

---

src/components/Tree/src/typing.ts
src/components/Tree/src/useTree.ts
src/utils/helper/treeHelper.ts

Subject of the feature
优化tree组件遍历函数支持批量插入子节点
Problem
当树节点非常大的时候，插入节点的函数出现性能不佳浏览器卡顿
api仅提供了插入单个子节点，插入多个节点重复调用性能较差
Expected behaviour
在treeHelper forEach中根据节点处理返回true及时终止无意义遍历
提供批量插入 insertNodesByKey

fix(comp-tree): support comp-tree-foreach stop,add insertNodesByKey

---

build/utils.ts

(cherry picked from commit bcc4773fbfc3dd1b7a24655bc731be830ad6d72d)
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] My changes generate no new warnings

fix: support various vite modes of build, not just production

---

src/router/guard/permissionGuard.ts

```ts
if (to.name === PAGE_NOT_FOUND_ROUTE.name) {
// 动态添加路由后，此处应当重定向到fullPath，否则会加载404页面内容
// fix: 添加query以免丢失
next({ path: to.fullPath, replace: true, query: to.query });
} else {
const redirectPath = (from.query.redirect || to.path) as string;
const redirect = decodeURIComponent(redirectPath);
const nextData = to.path === redirect ? { ...to, replace: true } : { path: redirect };
next(nextData);
}
```

fix(perm-guard): 修复刷新页面后路由 query 丢失的问题。

---

src/components/Qrcode/src/Qrcode.vue
src/components/Qrcode/src/drawCanvas.ts

fix(qrcode): Fix the problem that the QR code cannot be dynamically generated

---

src/components/Table/src/BasicTable.vue

文档中提到支持官方组件的expandIcon插槽，但实际无效。
因为默认强制设置了expandIcon函数，覆盖了expandIcon插槽。
需要增加一个条件，判断expandIcon插槽是否存在

fix: expandIcon slot of BasicTable component is invalid

---

src/utils/env.ts

fix: typo for utils/env

---

src/views/sys/iframe/index.vue

修复首次进入iframe路由页height计算错误问题
问题: 当进入路由后过渡动画未结束前iframe先加载完毕时, 上一个路由div还未销毁, 执行的calcHeight函数中getViewportOffset得到的top会算上上一个路由的高度,导致计算错误.

fix: fix iframe heigth error

---

src/components/Page/src/PageWrapper.vue
src/hooks/web/useContentHeight.ts

PageWrapper
为useContentHeight 添加 向上递归 移除差值 的功能。 pagewrapper添加 upwardSpace以支持向上递归功能。
此特性是为了兼容 PageWrapper 顶层（N层）具有`padding-bottom`|`margin-bottom`的情况（向上递归仅会排除`padding-bottom`|`margin-bottom`的值）

Feat(use content height)

---

src/components/Table/src/components/settings/ColumnSetting.vue

表格列设置ifshow为false，表格的列设置里依然会渲染该列的checkBox，实际应该不渲染。如果需要隐藏应该是设置defaultHidden。

解决表格列设置ifshow为false的bug

---

src/components/Tree/src/Tree.vue
src/components/Tree/src/TreeHeader.vue
src/components/Tree/src/props.ts

1. 修复expandOnSearch与checkOnSearch功能
2. 添加selectOnSearch功能
3. 添加搜索高亮title功能
4. 优化TreeHeader的样式表现: searchInput自动扩充
优化后示例图：

perf(tree): 优化Tree搜索功能，添加搜索高亮功能，优化样式表现

---

.eslintrc.js

chore:add rules

---

src/components/Table/src/components/settings/ColumnSetting.vue

修复去掉checkList 后，移动配置中的table顺序后，调用tabel.setColum() 时触发 init() ，导致checkList 被重置bug

修复去掉checkList 后，移动配置中的table顺序后，调用tabel.setColum() 时触发 init() ，导致checkList 被重置bug

---

src/components/Table/src/hooks/useTableFooter.ts
src/components/Table/src/hooks/useTableScroll.ts
src/components/Table/src/types/table.ts

1.修复table升级ant3.0导致无法自适应剩余高度
2.修复table升级ant3.0导致BasicColumn类型的title属性无法找到

fix: 修复table自适应高度和title属性声明问题

---

src/components/Table/src/hooks/useDataSource.ts

- 因为 `unref(dataSourceRef).splice(index, 0, record);  unref(propsRef).dataSource?.splice(index, 0, record);`同时存在时会导致添加俩条数据的情况发生；并且在 `useDataSource.ts` 中 line:60 `!api && dataSource && (dataSourceRef.value = dataSource);` 已经把 props 中的 `dataSource` 赋值给了 `dataSourceRef` 所以这里只保留 `unref(dataSourceRef).splice(index, 0, record);` 即可
- 注释掉 `if (!dataSourceRef.value || dataSourceRef.value.length == 0) return;` 的原因是因为 `dataSourceRef` 在初始化时已经给了默认值见 line:49 ；并且开发在使用时的场景是不论表格有没有数据使用了该方法那就是希望向表格中添加数据，所以注释掉了。
- 上述俩点我均在我们的项目中测试了接口返回异步数据与传入静态数据俩种情况已经通过测试。
> ℹ️ Check all checkboxes - this will indicate that you have done everything in …

fix(table component): reduce 'insertTableDataRecord' code logic

---

src/components/Table/src/BasicTable.vue
src/components/Table/src/hooks/useTableScroll.ts
src/components/Table/src/props.ts
src/components/Table/src/types/table.ts
src/locales/lang/en/routes/demo.ts
src/locales/lang/zh-CN/routes/demo.ts
src/router/routes/modules/demo/comp.ts
src/views/demo/table/ResizeParentHeightTable.vue

在保证了原有的高度计算上，额外新增继承父级高度， 只需设置isCanResizeParent：true

feat: 添加table继承父元素高度的功能

---

src/components/Table/src/components/editable/EditableCell.vue

修复EditCellTable组件 可编辑单元格当columns.ellipsis=false时，回调中取不到key的值。

fix: 修复EditCellTable 可编辑单元格当columns.ellipsis=true时，回调中取不到key的值。

---

src/components/Table/src/hooks/useDataSource.ts

当返回数据是数组时，fetch-success 返回  total 是0

fix:fetch-success total 0

---

src/components/Form/src/hooks/useFormValues.ts
src/views/demo/form/index.vue

添加对表单字段解构赋值的支持。某些表单组件的 value 值是 array 或者 object 类型，但是我们使用的时候却往往需要展开取值。如 RangePicker 返回 ['2012-12-1', '2022-1-2']， 而我们传给后端的往往是
`{ startTime: '2012-12-1'， endTime: '2022-1-2' }`。需要前端写很多难看的转换代码。
字段解构赋值可以在 field 字段声明如何解构和赋值。
```javascript
const schema = [
{
field: '[startTime, endTime]',
label: '时间范围',
component: 'RangePicker',
},
{
field: '{ name, level }',
label: '人员等级',
component: 'CustomPickerObjectValue',
},
]
// getFormValue 得到的就是 …
```

feat: make fields key of form deconstructable

---

src/components/Table/src/types/table.ts

新版本ant design vue的columnProps使用了泛型,导致xxx.data.ts里面定义的BasicColumn使用customRender地方全部报错

fix(table):basicColumn加泛型

---

stylelint.config.js

运行 `npm run lint:stylelint ` 命令时，less 内置函数会报 `function-no-unknown` 的错误

# fix: stylelint 检查 less 内置函数 function-no-unknown

---

build/vite/plugin/styleImport.ts

When i use `RangePicker` in Vue Component, not in `Form`.
Deploy project, jenkins will report error:
```
Rollup failed to resolve import "/build/node_modules/ant-design-vue/es/range-picker/style/index" from "src/components/DateInterval/index.vue".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
```

fix(styleImport): fix RangePicker build error

---

src/components/Tree/src/Tree.vue

框架的Tree组件未使用immediate方式监听value值，导致初次渲染出来，无法将选中的节点值赋值给antd的tree组件

fix: 修复tree组件初次渲染时无法应用已勾选的节点数组及一处字段名错误

---

src/hooks/setting/useMenuSetting.ts
src/layouts/default/sider/useLayoutSider.ts
src/settings/projectSetting.ts
types/config.d.ts

修复由于 layout sider 响应式下会隐藏，导致宽度计算有误问题。
复现页面：https://vvbin.cn/next/#/page-demo/form/high
页面宽度拖拽变窄后，页脚操作栏无法覆盖底部，所有导航栏模式均可复现

fix: 菜单响应式隐藏时宽度计算错误

---

src/views/demo/system/account/index.vue
src/views/demo/system/dept/index.vue
src/views/demo/system/menu/index.vue
src/views/demo/system/role/index.vue

fix: 修复 当窗口过窄时，表格中的删除确认框样式错乱 的问题

---

src/components/Table/src/BasicTable.vue

问题：表格中y轴滚动条总是一直出现。内容很少时，有滚动条出现，却不能滚动，表格body右侧跟表头不对齐，看起来就像缺一块

style: 优化滚动条显示，只有在内容超过显示高度时才会出现

---

build/script/buildConf.ts

当下如果在ENV中：
```
VITE_GLOB_APP_TITLE="hello world"
```
那么在prod build时候，配置中的值会丢失空格，Title会变成 `helloworld`.
这个PR修复了这个问题。
---

fix: 修复ENV配置在prod丢失空格问题

---

src/views/demo/page/form/high/PersonTable.vue
src/views/demo/system/account/index.vue
src/views/demo/system/dept/index.vue
src/views/demo/system/menu/index.vue
src/views/demo/system/role/index.vue
src/views/demo/table/AuthColumn.vue
src/views/demo/table/CustomerCell.vue
src/views/demo/table/EditRowTable.vue
src/views/demo/table/ExpandTable.vue
src/views/demo/table/FixedColumn.vue
src/views/demo/table/FixedHeight.vue
src/views/demo/table/tableData.tsx
src/views/sys/error-log/index.vue

彻底修复column.slots已废弃的antd报错, 所有用到的demo页修改为antd 3.x v-slot:headerCell 和 v-slot:bodyCell 写法;
并修复#1705 的改动引起的定高/头部自定义页面的bug

fix(table): 彻底修复column.slots已废弃的antd报错, 所有用到的demo页修改为antd 3.x写法

---

src/views/demo/table/ExpandTable.vue

[#2030 ](https://github.com/vbenjs/vue-vben-admin/pull/2030)改动后，ExpandTable demo页面达不到预期了。
此pr修改前
此pr修改后
控制台也没有slot的警告，因为这个不属于column.slots

fix: 修复#2030改动引起的可展开table失效

---

build/vite/plugin/index.ts
build/vite/plugin/styleImport.ts
src/main.ts

能力有限，没办法根治这个问题，能用而已，供大家参考解决
经测试是`vite-plugin-vue-setup-extend`、`vite-plugin-style-import`两个插件引起的，注释插件后，发现antdv样式没引用进来，尝试使用[unplugin-vue-components](https://github.com/antfu/unplugin-vue-components)，没有效果，能力有限，只好暂时在main.ts全量引入antdv样式，希望有能力的童鞋继续修复这个问题。

修复debugger位置、断点位置与调试位置不一致，导致没法调试

---

src/components/Tree/src/BasicTree.vue
src/components/Tree/src/types/tree.ts
src/views/demo/system/account/DeptTree.vue

背景：目前BaseTree缺少对外层的样式控制，导致DeptTree.vue中的tree在窗口小的情况下无法添加滚动条样式。
方案：在BaseTree.vue的440行的使用spin组件wrapperClassName的属性，使其样式自定义，其值从BaseTree组件props获取。

feat: 对BaseTree组件新增treeWrapperClassName属性

---

build/vite/plugin/styleImport.ts

直接引用 `ATextarea ` 会导致样式 import 报错
```js
import { Textarea } from 'ant-design-vue';
```
最小复现案例在 https://github.com/hunshcn/vue-vben-admin/tree/reproduce/textarea-style-import 

fix(vite-plugin-styleImport): fix ATextarea 直接引用出现样式导入错误的问题

---

src/components/Table/src/hooks/useCustomRow.ts
src/components/Table/src/hooks/useRowSelection.ts
src/views/demo/table/FormTable.vue

1. demo中在`组件-Table-开启搜索区域`页面里，直接点击`列设置`中的`勾选列`，会报空指针错误
2. 修复上述空指针错误后，可成功显示/隐藏checkbox列；但是从第二次切换显隐开始，绑定的selectedRowKeys响应式丢失，看了`useRowSelection.ts`源码后猜测是因为demo中是直接通过props传入`rowSelection`配置，在第一次切换`checkbox`列后引用更改导致的响应式丢失。

fix: 修复demo中formTable几个空指针报错和selectedRowKeys丢失响应式的问题

---

src/components/Cropper/src/CopperModal.vue

fix: 裁剪上传接口与uploadModal统一：url

---

src/components/Form/src/hooks/useFormValues.ts

按照条件筛选表格数据，点击重置后请求的接口会带上某个筛选数据的字段，如 `xxx/info?page=1&pageSize=10&customParams=`, 而不是`xxx/info?page=1&pageSize=10`
原因是当 reset form后，default value 是 empty string，导致带上了参数

fix: 重置表单时移除URL中的参数

---

src/components/Tree/src/types/tree.ts

使用Tree组件时, 如果设置checkStrictly为true, 控制台会打印props类型异常警告
通过调整checkedKeys属性类型定义解决警告问题

🐞 fix(Tree): 调整checkedKeys属性的类型

---

src/layouts/page/index.vue
src/views/form-design/index.vue

1. 修复页面不能缓存的bug
2. 此更新为破坏性更新，页面不支持多标签使用
3. 将表单设计模块多标签改成单标签

fix: 修复页面缓存不生效的问题

---

src/utils/http/axios/Axios.ts

cancelToken 如果被深拷贝，会导致最外层无法使用cancel方法来取消请求

fix 主动调用 axioscancelToken 的 cancel 取消请求时 无效的问题

---

src/components/Table/src/BasicTable.vue
src/components/Table/src/components/settings/ColumnSetting.vue
src/components/Table/src/hooks/useColumns.ts
src/components/Table/src/types/table.ts

此`pr`更改前，`columnSetting`组件存在但不限于几个问题
- 组件内的操作会产生bug，比如[useTable demo中](https://vben.vvbin.cn/#/comp/table/useTable)，把姓名列，拖动到最后，然后勾选列展示，展示全部columns，则发生顺序错乱
- 更改Columns，`columnSetting`组件并不会更新
此`pr`主要是对`columnSetting`组件(下面统称为**组件**)的操作逻辑进行重构
- `组件`内所有操作产生的顺序、固定、是否展示列等，table会做出预期的反应
- 外部更改Columns配置(即不是`组件`内操作所产生的columns)，组件会同步更新
- `组件`的重置按钮，重置的是`组件`内部操作之前的配置
其实非常难形容，最好是能够拉代码跑一跑

refactor: 完善ColumnSetting的操作逻辑

---

internal/vite-config/src/plugins/appConfig.ts
src/hooks/setting/index.ts
src/utils/env.ts

#1522 
bug: `.env`中的配置项`VITE_GLOB_APP_TITLE(全称)`若出现了`-`则无法加载进登陆界面, console报错`Cannot destructure property 'VITE_GLOB_APP_TITLE' of 'C' as it is undefined.`
why: 查看文档以及代码发现`VITE_GLOB_APP_SHORT_NAME(简称)`项被定义但未被使用, 代码中所有需要用到`VITE_GLOB_APP_SHORT_NAME(简称)`的地方全都是replace得到的: `VITE_GLOB_APP_TITLE.replace(/\s/g, '_')`
代码中只替换了空格, 而未替换`-`, 所以造成了使用`VITE_GLOB_APP_SHORT_NAME(简称)`的地方可能会出现`-`导致无法加载的问题
本pr修复了该问题, 使得可以在`VITE_GLOB_APP_TITLE(全称)`中使用`-`
---

fix: 修复VITE_GLOB_APP_TITLE中不能存在-的问题#1522

---

internal/stylelint-config/src/index.ts

perf: 解决提交代码时stylelint格式化less和scss的媒体查询为不支持的语法(Media Queries Level 4)

---

src/components/Form/src/components/FormItem.vue
src/components/Form/src/hooks/useFormEvents.ts
src/components/Form/src/hooks/useFormValues.ts
src/components/Form/src/types/form.ts
src/utils/helper/tsxHelper.tsx
src/views/demo/form/CustomerForm.vue

feat: Form 自定义组件渲染 示例： /comp/form/customerForm页面
1. 针对自定义渲染功能 FormSchema 中
render, renderColContent, renderComponentContent 新增 opts:{disabled} 扩展 帮助自定义渲染时做 条件判断、展示同步
渲染: ((renderCallbackParams) => any) ===> ((renderCallbackParams, opts) => any)
2. slot, colSlot 分别是 render, renderColContent 插槽，为方便插槽使用
slotFn 进行解构 #test={scope} scope==={...data, ...opts}
示例： /comp/form/customerForm页面

feat: Form 自定义组件渲染 新增 opts: {disabled} 用于自定义渲染判断 示例： /comp/form/customerForm页面

---

packages/hooks/src/useRefs.ts

useRefs函数目前只接收el:HTMLElement类型，可不可以转换成泛型去接收类型。
例如使用在组件模版上，把组件类型传入useRefs，这样在后续使用中就可以获取到准确的组件类型，例如：
```
<template>
<MyModal 
:ref="setRefs(index)"
v-for="(item, index) in searchResult"
:key="item.path"
/>
</template>
import { useRefs } from '@vben/hooks';
import MyModal from './MyModal.vue'
const { refs, setRefs } = useRefs<InstanceType<typeof MyModal>>();
</script>
```

perf: useRefs函数接收泛型类型

---

src/components/CardList/src/CardList.vue
src/components/Form/src/hooks/useFormEvents.ts
src/views/form-design/components/VFormDesign/modules/FormComponentPanel.vue

-  修复了重置后的 range slider 组件的默认值为**数组**。
- 对获取组件默认值的函数进行了重构。
-  Typography.Text 的 ellipsis 属性只接受布尔类型的值，**删除ellipsis属性**或**换成Paragraph组件**就不再有闪烁了
- 修复表单设计页面容器的问题：当容器内的内容超过页面高度时，没有出现垂直滚动条

fix: #2767 #2884 #2868

---

src/components/Form/src/hooks/useFormValues.ts

为fieldMapToTime的第三个参数增加 timestamp 和 timestampStartDay 选项
- timestamp的作用: 将映射的时间格式转为时间戳
- timestampStartDay的作用： 将映射的时间格式转为当天0点开始的时间戳
增加 timestampStartDay 是必要的，因为 Antd 日期选择器组件即使在禁用时间功能时，输出的值仍包含组件创建时的时分秒。通过添加 timestampStartDay 选项，可以确保输出值只包含组件创建时的日期部分。
ElementUI的日期选择器没有这样的问题，可能是我用惯它了 😆

feat(Form): 为fieldMapToTime的映射类型增加时间戳转换

---

src/components/Page/src/PageWrapper.vue

pageWrapper props加入两个选项
pageWrapper props add two options
```ts
headerSticky: boolean,
headerStyle: Object as PropType<CSSProperties>,
```
用于控制pageWrapper是否粘附在顶部
use to control wheher pageWrapper header is sticky to the top

feat: pageWrapper组件加入sticky功能

---

src/components/Drawer/src/BasicDrawer.vue
src/components/Drawer/src/typing.ts

因为v4版本配置外层class的属性变更，导致详情页模式下的 drawer组件会全屏覆盖

style(Drawer): antdv4版本 drawer要使用rootClassName来来配置最外层元素样式

---

.eslintrc.js
src/components/Table/src/BasicTable.vue
src/components/Table/src/components/editable/CellComponent.ts
src/components/Table/src/hooks/useColumns.ts
src/components/Table/src/hooks/useDataSource.ts
src/components/Table/src/hooks/useRowSelection.ts
src/components/Table/src/hooks/useTable.ts
src/components/Table/src/hooks/useTableExpand.ts
src/components/Table/src/hooks/useTableScroll.ts
src/components/Table/src/types/table.ts
src/views/form-design/components/VFormDesign/components/CodeModal.vue
src/views/form-design/components/VFormDesign/components/ImportJsonModal.vue
src/views/form-design/components/VFormDesign/components/JsonModal.vue
src/views/form-design/components/VFormPreview/index.vue
src/views/form-design/components/VFormPreview/useForm.vue

- 关闭eslint的no-undef规则校验，eslint识别不到ts定义的全局类型，直接用ts编译器进行校验就可以
- 处理basicTable组件的一些类型问题,主要是一些函数参数的类型不对应
- 替换一些引用modal示例文件的visible属性
- 替换可编辑表格行引用popover组件的visible属性

chore: 解决 ESLint no-undef 规则校验问题和 basicTable 组件的类型问题，替换popover组件的 visible 属性。

---

src/hooks/web/usePermission.ts

目前看，按钮权限是数组，满足数组中一个的话，就会显示按钮权限。但没有全部满足才展示的判断，有时候需要组合判断，
如v-auth="'checked&&unchecked'"。

perf: 指令权限v-auth支持并显示按钮权限

---

src/components/Form/src/components/FormItem.vue

feat: 解决Form组件slot必须传递component字段才显示的问题

fix: 解决Form组件slot必须传递component字段才显示的问题

---

src/components/Form/src/components/ApiSelect.vue
src/components/Form/src/helper.ts

问题是出在ApiSelect change事件没有主动触发外部的change事件，导致首次Form.Item收集不到change的值
其次
https://github.com/vbenjs/vue-vben-admin/blob/1cf2a81f2a407ed73f9e22daa752600c5017801e/src/components/Form/src/components/FormItem.vue#L359
```
// TODO 自定义组件验证会出现问题，因此这里框架默认将自定义组件设置手动触发验证，如果其他组件还有此问题请手动设置autoLink=false
if (NO_AUTO_LINK_COMPONENTS.includes(component)) {
props.schema &&
(props.schema.itemProps! = {
autoLink: false,
...props.schema.itemProps,
});
}
```
再看下autoLink属性的作用 ApiSelect组件本就是单一元素节点，所以**NO_AUTO_LINK_COMPONENTS**的设置有些多余，故删去

fix(ApiSelect):  ApiSelect首次选择值时仍然提示校验, fix #3065

---

src/components/Modal/src/index.less

antd4版本的 ant-modal-footer样式默认有个margin-top，全屏下去除掉显示就正常了

style(Modal): modal全屏模式 ant 的modal-footer margin-top调整为0, fix #3069

---

src/components/Form/src/components/FormItem.vue
src/components/Form/src/helper.ts

修复rule validator类型默认为string，导致 radio 等组件在 setFormValues 时，如果值不是string类型，提示校验错误

fix: 修复rule validator type默认为string

---

src/components/Form/src/components/ApiTransfer.vue

fix: #3077 最新代码 ApiTransfer编辑后无法正常显示数据

---

src/hooks/web/useWatermark.ts
src/views/demo/feat/watermark/index.vue

- 不再使用**weakmap**来管理水印信息, 应该让用户自主管理清除操作
- 不再使用ID来绑定dom, 支持设置多重水印
- 补充演示示例

feat: 支持设置多重水印，增加清除所有水印方法. close #2610

---

src/views/demo/table/AuthColumn.vue

因为**TableAction**为固定列，所以导致部分情况下会有表头错位的问题， 按**antdv**说的给**column**加个 **width**就能解决

chore: 设定权限列columns宽度，消除演示表格错位问题. close #3085

---

internal/vite-config/package.json
internal/vite-config/src/utils/modifyVars.ts
package.json
pnpm-lock.yaml
src/components/Form/src/components/ApiTransfer.vue

vite-config中将ant-design-vue升级到版本4

---

.vscode/extensions.json

可以看到vscode未正确解析 **/@/**这样的路径。
引入 [TypeScript Vue Plugin (Volar)](https://marketplace.visualstudio.com/items?itemName=Vue.vscode-typescript-vue-plugin) 这个vscode扩展可以解决此问题
安装该扩展后
鼠标点击可以进行正常调整

perf: 解决ts文件通过alias引入vue文件后, vscode调转不到正确vue文件路径

---

internal/vite-config/package.json
internal/vite-config/src/plugins/appConfig.ts
pnpm-lock.yaml

chore: update `unplugin-config`

---

src/components/Container/src/ScrollContainer.vue
src/components/Modal/src/components/ModalWrapper.vue
src/components/Scrollbar/src/Scrollbar.vue

fix: ScrollContainer的一个问题 #3046

---

src/layouts/default/header/MultipleHeader.vue
src/layouts/default/tabs/index.vue
src/layouts/default/tabs/useMultipleTabs.ts

-  处理 #2744 选项卡渲染问题
-  按照源码逻辑，如果路由的meta中affix为true的时候，该tab时不能拖拽的。修复此逻辑（源码中没有使用国际化导致sortablejs无法filter，此PR已做修改）

fix: #2744tabs选项卡渲染问题，以及完善路由中affix=true时处理逻辑。

---

src/components/Menu/src/components/MenuItemContent.vue
src/components/SimpleMenu/src/SimpleSubMenu.vue
src/layouts/default/sider/MixSider.vue
src/router/types.ts
types/vue-router.d.ts

feat(Menu): Add custom images to menu 

---

mock/demo/system.ts
src/views/demo/system/account/account.data.ts

fix(demo): account page table without dept

---

src/components/CardList/src/CardList.vue
src/components/Form/src/components/ApiTree.vue
src/components/Menu/src/BasicMenu.vue
src/components/Menu/src/props.ts
src/components/Menu/src/types.ts
src/components/Menu/src/useOpenKeys.ts
src/components/Scrollbar/src/Scrollbar.vue
src/components/Table/src/hooks/useCustomRow.ts

- `wrapStyle`本身就可以直接赋给组件上的`style`属性，额外的计算开销。
- `style`不支持`wrapStyle = [{ background: 'red' }, 'fontSize: 16px']`。
```js
const style = computed(() => {
// 例 wrapStyle = [ { background: 'red' }, { background: 'green' } ]
// style和wrapStyle 效果一致
if (Array.isArray(props.wrapStyle)) {
return toObject(props.wrapStyle);
}
return props.wrapStyle;
});
```

chore: fix type:check error

---

package.json
pnpm-lock.yaml
src/store/index.ts
src/store/plugin/persist.ts

feat: add pinia persist plugin

---

src/enums/cacheEnum.ts
src/hooks/setting/useHeaderSetting.ts
src/layouts/default/header/components/ChangeApi/index.vue
src/layouts/default/header/components/user-dropdown/index.vue
src/locales/lang/en/layout.json
src/locales/lang/zh-CN/layout.json
src/settings/projectSetting.ts
src/store/modules/app.ts
src/utils/env.ts
types/config.d.ts
types/store.d.ts

_app.config.js上线后修改API地址，需要在此这里改有点不方面；有时候不想部署多套环境或者临时使用其他环境，希望可以直接在站内切换API换成其他环境。

站内支持API接口地址切换

---

src/components/Upload/src/FileList.vue
src/components/Upload/src/UploadModal.vue
src/components/Upload/src/UploadPreviewModal.vue
src/components/Upload/src/data.tsx
src/components/Upload/src/typing.ts
src/locales/lang/en/component.json
src/locales/lang/zh-CN/component.json

fix(Upload): The file name is too long bug

---

src/components/Tree/src/types/tree.ts

修复路由`comp/tree/basic`页面第二个默认展开案例的bug。
参照文档[antdv](https://antdv.com/components/tree-cn/#Tree)，如果有`expandedKeys prop`（即源码中的不为`undefined`），`defaultExpandAll prop`会失效。
```js
// components/vc-tree/Tree.tsx
if (
props.expandedKeys !== undefined ||
(init && newAutoExpandParent !== oldAutoExpandParent)
) {
// ...
} else if (!init && props.defaultExpandAll) {
// ....
}
```

fix(tree): remove expandedKeys prop default value

---

src/views/demo/form/RuleForm.vue
src/views/demo/system/account/account.data.ts

之前每次输入都触发，由于是请求接口，不保证接口的响应顺序，因此输入过快时可能不会触发校验（比如内容为`admi`的接口响应比内容为`admin`慢）

fix: async validator

---

src/components/Form/src/components/FormItem.vue

`antdv`中`DatePicker、 RangePicker`的`getPopupContainer`有默认值，无需额外做默认值处理。
修复以下几个页面中日期选择悬浮弹窗错位
- comp/form/refForm
- comp/form/advancedForm
- comp/form/ruleForm

fix(FormItem): use getPopupContainer default value

---

src/router/helper/routeHelper.ts

修复transformObjToRoute方法，在某些情况下name可能没有值，此时路由name值为undefinedParent，会导致 多个一级路由菜单会页面404

fix(routeHelper.ts): Route name may be undefined

---

src/views/demo/form/CustomerForm.vue

```
renderColContent({ model, field }, { disabled }) {
return (
<FormItem
name="typeKey"
label="复合field renderColContent"
rules={custom_typeKey2typeValueRules(model)}
>
<Input.Group compact>
<Select
allowClear
disabled={disabled}
style="width: 120px"
v-model:value={model[field]}
>
<Select.Option value="公司名称">公司名称</Select.Option>
<Select.Option value="产品名称">产品名称</Select.Option>
</Select>
<FormItemRest>
<Input
style="width: calc(100% - 120px); margin-left: -1px;"
placeholder="请输入"
v-model:value={model['typeValue']}
disabled={disabled}
/>
</FormItemRest>
</Input.Group>
</FormItem>
);
}
```
这么写可以避免控制台展示一下提示
```
index.ts:41 Warning: [ant-design-vue: Form.Item] FormItem can only collect one field item, you haved set `ASelect`, `AInput` 2 field items.
You can set not need to be collected fields …
```

fix: FormItem下有多个受控组件控制台显示错误提示的bug

---

src/locales/lang/zh_CN.ts

fix(DatePicker): zh-CN is not work in DatePicker

---

src/components/Form/src/helper.ts

fix: defaultValue类型为number时, 点击编辑 setFieldsValue的值会被覆盖掉  #3274
closes #3274 

fix: defaultValue类型为number时的bug

---

src/views/form-design/components/VFormDesign/config/componentPropsConfig.ts

修复`idx`为`-1`时，走进第二个`if`语句报错（`props[idx].componentProps`

fix(VFormDesign): findIndex === -1

---

src/components/Form/src/hooks/useFormEvents.ts

修复 setFieldsValue 方法设置完值后，当表单属性 componentProps 为 function 时会丢失formActionType 的bug

fix(useFormEvents): 修复setFieldsValue 方法设置完值后，表单属性丢失formActionType 的bug

---

src/hooks/web/usePage.ts

fix(breadcrumb): 修复面包屑跳转外链时，导致当前页面404问题 https://github.com/vbenjs/vue-vben-admin/issues/3336#issue-2009164377
在点击面包屑时判断path是否为http协议，如果是http协议直接另开窗口打开，当前页面路由不做操作

fix(breadcrumb): 修复面包屑跳转外链时，导致当前页面404问题

---

src/components/Form/src/BasicForm.vue

在BasicForm.vue文件中有如下源码
当我们先使用updateSchema对schemas进行修改
然后使用setProps更新from的props
此时由于getProps来自props的深拷贝，props.schemas的数组引用发生变化，图中监听器必然触发，导致schemaRef被重置，
出现问题
1. (https://vben.vvbin.cn/#/comp/form/useForm)以此页面为例
2. 我们可以移除字段4的选项，然后在onMounted中使用updateSchema为其传入options
3. 然后我们调用setProps修改任意formprops,我们会发现字段4没有选项
4. 移除setProps,选项出现

fix: 解决Form updateSchema后执行setProps导致schemaRef被重置的问题

---

src/components/Form/src/BasicForm.vue

当DatePicker使用箭头函数返回配置数据时无法正常显示日期 
```
{
field: 'field3',
component: 'DatePicker',
label: '字段3',
defaultValue: '2023-11-28',
colProps: {
span: 8,
},
// componentProps: {
//   valueFormat: 'YYYY-MM-DD',
//   format: 'YYYY-MM-DD',
// },
componentProps: (opt) => {
return {
valueFormat: 'YYYY-MM-DD',
format: 'YYYY-MM-DD',
};
},
},
```

修复BasicForm使用componentProps函数返回valueFormat时DatePicker无法正确格式化的问题 

---

src/components/Table/src/components/settings/ColumnSetting.vue

> 关于反馈：动态调整列（setColumns）会导致错误；以及我发现执行多次 setColumns 会导致严重错误；还有 Sortablejs 的实例 sort 方法执行后出现无法理解的排序异常。特别地赶紧修复一波，思路是：Sortablejs 的实例实际由缓存记录的 ref 实例化（浮窗再次显示不会再次实例化），初始排序已经是符合预期的，无需使用 Sortablejs 的实例 sort 方法、无需记录排序。

fix: ColumnSetting mistake when use setColumns

---

src/components/Form/src/components/FormItem.vue
src/components/Form/src/props.ts
src/components/Form/src/types/form.ts
src/views/demo/table/tableData.tsx

This reverts commit 1ca3f7c2c0c0c00e8395e26c59796c875d34e12c.
[#3378](https://github.com/vbenjs/vue-vben-admin/pull/3378), 之前提交的这个PR, 存在以下问题
- reload的时候没有带上参数
- change会覆盖changeEvent事件，导致点搜索无法带上参数
另外发现submitOnChange=true就可以实现值改变的时候触发table重新请求，所以请求回滚代码。

Revert "feat: table搜索表单值发生改变可以触发reload (#3378)"

---

src/components/Icon/src/IconPicker.vue

> 图标选择器理应可以 allowClear，附带 readonly 也应该可以设置，尤其在作为 Form -> FormItem -> Component 的时候。否则选择图标之后，就完全没有办法清除值了，非 required 的时候就出问题了。

feat: IconPicker could allowClear and readonly for form

---

src/layouts/default/tabs/index.less

> 请问，下面 tabs 的 bottom 的”双眼皮“是故意如此设计的么？
> 如果是，麻烦关闭此 request 即可，谢谢~

style: tabs bottom double line fix

---

src/components/Drawer/src/BasicDrawer.vue

> 使用 Drawer 的时候，在组件内部使用 getOpen 获取是否打开状态，发现 build 之后没有生效。对比build前后代码，关键逻辑丢失，如下：
> 不考虑 build 配置，微调判断可以避免这个问题。

fix: watch open logic lost after build

---

src/components/Table/src/components/settings/ColumnSetting.vue
src/components/Table/src/components/settings/index.vue
src/components/Table/src/types/table.ts

> 经过反馈，启用 ColumnSetting 之后，默认情况下，无法使用 rowSelections；经过分析测试，是赋值 selectedRowKeys 导致的。此 pr 就是修复这个问题。顺便把 cache 开关增加 TableSettings 可以单独设置。
> 反馈来源与分析，https://github.com/vbenjs/vue-vben-admin/issues/3445
> 也意味着，目前 selectedRowKeys 受 useRowSelection 管理，不能自行设置 selectedRowKeys，需要通过 useRowSelection 的方法控制 selectedRowKeys。

fix: ColumnSetting about selectedRowKeys override

---

src/components/Table/src/components/settings/ColumnSetting.vue

> 当开启了ColumnSetting的缓存，将 showIndexColumn 从 true 改变成 false 的时候，序号列依旧显示，理应不显示。

fix: index still show when set showIndexColumn false

---

src/components/Table/src/hooks/useRowSelection.ts

> 保留外部 rowSelection.onChange 的回调，为了解决 https://github.com/vbenjs/vue-vben-admin/issues/3453

fix: keep rowSelection onChange call outside

---

src/components/Form/src/hooks/useFormEvents.ts
src/components/Form/src/types/form.ts

当使用fieldMapToTime转换一个form表单的值时，如果有默认值的情况下，假设有一个input框在输入时需要使用updateSchema时，会把我刚选择的日期又变回默认值，这不是我预期的结果。
When using fieldMapToTime to convert the value of a form, if there is a default value, assuming there is an input box that needs to use updateScheme for input, it will change the date I just selected back to the default value, which is not the result I expected.

fix: 修复搜索表单使用updateSchema时，如果使用fieldMapToTime引起的bug

---

src/components/Table/src/components/editable/EditableCell.vue

> 当同时开启了表格的 rowSelection 和 cell edit 功能，cell edit 操作会穿透、触发 select 操作，所以修复之。
> 修复包括：修改前、修改中、修改 Loading中 三个情况

fix: avoid select when edit cell

---

src/components/Table/src/components/settings/ColumnSetting.vue
src/store/modules/tableSetting.ts
types/store.d.ts

> 列设置的序号列、选择列在不同页面之间存在干涉，逻辑错误，缓存记录也应该根据路由隔离，现修复之。
> 错误场景具体描述：在打开列设置的缓存功能的情况下，假设页面 A、B 均显示选择列，此时任意隐藏其中一个页面的选择列，另外一个页面的选择列也消失了。

fix: showIndexColumn/showRowSelection cache by route name

---

src/components/Form/src/hooks/useFormEvents.ts
src/components/Form/src/hooks/useFormValues.ts

handleFormValues 在获取 fields 时调用，判断字段为空字符串时会转换为 undefined，但这样就无法将有内容的字符串修改为空字符串值，因为 json 序列化会忽略 undefined 字段
之前这里的修改是 [为了重置表单时移除URL中的参数 #2559](https://github.com/vbenjs/vue-vben-admin/pull/2559/)
在 resetFields 里调用的 getDefaultValue 里把 input 默认值设置为 undefined 一样可以实现

fix: handleFormValues 不再将所有空字符串转换为undefined

---

src/router/routes/modules/about.ts

fix: menu->about icon is missing

---

src/components/Form/src/components/ApiCascader.vue

> 避免使用 watchEffect，这里因为外部 updateSchema 触发了多余的 api reload了。（https://github.com/vbenjs/vue-vben-admin/issues/3534）

fix(ApiCascader): wrong api reload

---

src/components/Form/src/components/FormItem.vue
src/components/Form/src/types/form.ts
src/views/demo/form/index.vue

(cherry picked from commit abd6e2b1298712e58cc69cdaa55f44e3393b71a5)

perf(component): formItem: label支持函数渲染

---

src/components/Form/src/components/FormItem.vue

> 根据 https://github.com/vbenjs/vue-vben-admin/issues/3570 排查得知，FormItem 内部是先触发表单组件的 event，后更新 model，导致 getFormValues 及其依赖了它的例如 reload 方法没有获得最新的 model 值。现调整为优先更新 model。

fix(FormItem): model should update before event call

---

src/hooks/web/usePermission.ts
src/router/guard/permissionGuard.ts
src/store/modules/user.ts
src/utils/http/axios/checkStatus.ts
src/utils/http/axios/index.ts
src/views/sys/lock/LockPage.vue

> 根据反馈 https://github.com/vbenjs/vue-vben-admin/issues/3588 重现问题，根源：
> src\store\modules\user.ts 重复并提前执行了 permissionStore.setDynamicAddedRoute(true)，导致 src\router\guard\permissionGuard.ts 无法通过到逻辑最后（不知道理解的对不对，测试通过部分场景）。
> 另外，目前登出均为 logout(true)，理应区分”主动“和”被动“两种场景，”主动“不带 redirect 回到登陆页，”被动“带。

fix: repair login about redirect query

---

src/components/Button/src/PopConfirmButton.vue

> 修复从 https://github.com/vbenjs/vue-vben-admin/commit/e6a73840ab7c7cbd5a5a534bd248f5ed5df11e5c 之后引起的类型报错，且避免使用 delete 语法。

fix(PopConfirmButton): avoid type lint error

---

src/hooks/web/useWatermark.ts
src/views/demo/feat/watermark/index.vue

- [ x ] Pull request template structure not broken
- [  ] This change requires a documentation update

feat(function): add watermark custom style

---

src/components/Modal/src/components/Modal.tsx

fix: basemodal 无法透传 attributes 至 Modal.tsx.
close #3636 
可以在 <script setup> 中使用 useAttrs() API 来访问一个组件的所有透传 attribute 。 如果没有使用 <script setup>，attrs 会作为 setup() 上下文对象的一个属性暴露，这边修改了透传 attribute 的方式。

fix: basemodal 无法透传 attributes 至 Modal.tsx

---

src/components/Form/src/BasicForm.vue

这个bug产生的原因是在computed中直接修改了依赖对象的defaultValue属性
closed #3649
- [] I have commented my code, particularly in hard-to-understand areas

fix(component): resolve the defaultValue error in setting the date type

---

apps/test-server/service/FileService.ts

问题好像出在koa对于form-data的上传数据结构变了，按照原来的代码在test-server下面启动并且上传文件会有如下报错，查看了一下目前的数据结构是 PersistentFile 
```shell
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
at ReadStream (node:internal/fs/streams:171:5)
at new ReadStream (E:\myProject\vue-vben-admin\node_modules\.pnpm\graceful-fs@4.2.11\node_modules\graceful-fs\graceful-fs.js:299:28)
at Object.createReadStream (E:\myProject\vue-vben-admin\node_modules\.pnpm\graceful-fs@4.2.11\node_modules\graceful-fs\graceful-fs.js:341:12)
at fileFunc (E:\myProject\vue-vben-admin\apps\test-server\service\FileService.ts:13:23)
at FileService.<anonymous> (E:\myProject\vue-vben-admin\apps\test-server\service\FileService.ts:49:7)
at Generator.next (<anonymous>)
at …
```

fix(koa->upload): fix the error that occurs when uploading files in the `test server` of Koa.

---

src/components/Form/src/components/ApiCascader.vue
src/components/Form/src/components/ApiRadioGroup.vue
src/components/Form/src/components/ApiSelect.vue
src/components/Form/src/components/ApiTransfer.vue

prop中存在resultField 这种支持xx.xx.xx类型。那么api的返回值应该包含 recordbale 类型

feat(type->api): resultField推断api的返回值应该包含recordbale类型

---

src/components/Upload/src/BasicUpload.vue
src/components/Upload/src/components/FileList.vue
src/components/Upload/src/components/ImageUpload.vue
src/components/Upload/src/components/UploadModal.vue
src/components/Upload/src/components/UploadPreviewModal.vue
src/components/Upload/src/props.ts
src/components/Upload/src/types/typing.ts
src/views/demo/comp/upload/index.vue

feature
- 1.添加 `upload`和`imgupload`组件 `resultField`的传参，用户可以自己定义返回的值(之前默认是`url`)
- 2.添加 `upload` 组件的 `previewColumns` 数据(`basicTable`格式)，和beforePreviewData(函数格式)两个传参,前者用来定义预览组件的table显示什么，后者可以对预览组件的数据进行一次预处理
- 3.添加了这些upload组件的示例文件，路由位置位于`http://localhost:5173/#/comp/upload` ，组件位置位于 `src/views/demo/comp/upload/index.vue`

feat(feature):upload->preview & upload->resultfield

---

src/components/Tree/src/types/tree.ts

basicTree组件设置clickRowToExpand为true，且不设置expandedKeys时，当点击row时报错，经查发现expandedKeys为undefined；
报错信息如下：
```
runtime-core.esm-bundler.js:254 Uncaught TypeError: Cannot read properties of undefined (reading 'includes')
at handleClickNode (BasicTree.vue:268:33)
at callWithErrorHandling (runtime-core.esm-bundler.js:192:19)
at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:199:17)
at HTMLSpanElement.invoker (runtime-dom.esm-bundler.js:681:5)
```
> 👉 _Put an `x` in the boxes that …

fix(component): resolve the error when clicking on a row when clickRowToExpand is true

---

src/components/Form/src/hooks/useFormEvents.ts
src/layouts/default/header/components/Breadcrumb.vue

The breadcrumb is initially hidden when accessing either the hidden menu or the "not found" page. However, upon returning to either the hidden menu or the "not found" page after navigating to other pages, the breadcrumb remains visible.

fix: breadcrumb is displayed despite the menu being hidden

---

src/components/Table/src/hooks/useTableScroll.ts

while 循环到body后导致 modalElIterator可能为空，下面语句执行报错。

fix: modalElIterator可能为空，导致报错

---

src/components/Form/src/hooks/useAdvanced.ts
src/views/demo/form/AdvancedForm.vue

需求：表单折叠除了动态计算表格高度之外，比如在一些非表格的页面也需要根据表单的高度动态计算列表（如：CardList）的高度，可以进行页面高度自适应

feat(BasicForm): 监听表单收缩方法传值进行判断

---

src/router/helper/routeHelper.ts

修复一级路由 `component` 非 `LAYOUT` （并且是`homePath`），当 url 为 `http://localhost:5174/#/` 时为空白页

fix(router): the issue of blank page navigation during repair of non-LAYOUT first-level route component

---

src/views/demo/form/index.vue

- form 的远程搜索的demo中用了一个debounce，但是这个函数永远不会被触发

fix(demo): 修复form demo的远程搜索不会触发的bug

---

src/components/Form/src/hooks/useFormEvents.ts

fix https://github.com/vbenjs/vue-vben-admin/issues/3774 & pref the code

fix: solve the error about setFieldValue array  & pref the code

---

src/components/Form/src/components/ApiCascader.vue
src/components/Form/src/components/ApiRadioGroup.vue
src/components/Form/src/components/ApiSelect.vue
src/components/Form/src/components/ApiTransfer.vue
src/components/Form/src/components/ApiTree.vue
src/components/Form/src/components/ApiTreeSelect.vue

about:https://github.com/vbenjs/vue-vben-admin/issues/3542
feature 
- 给 ApiCascader | ApiRadioGroup | ApiSelect | ApiTransfer | ApiTree | ApiTreeSelect 统一添加beforeFetch 和 afterFetch方法
fix
- 修复ApiTree和ApiTreeSelect关于resultfield的判定和使用

feat:add beforeFetch & afterFetch to apicomp && perf the code

---

src/components/Form/src/helper.ts

修复 SetFieldsValue 设置值时，会将 Number 类型的值转为 string 的问题

更新 SetFieldsValue 方法

---

src/components/Form/src/helper.ts
src/components/Form/src/hooks/useFormEvents.ts

fix:https://github.com/vbenjs/vue-vben-admin/issues/3805
Pull request template structure not broken
历史遗留问题
当初这个函数的提出是为了解决这个默认值的bug( https://github.com/vbenjs/vue-vben-admin/issues/3274 )，但是默认值的问题没有彻底解决
直到 https://github.com/vbenjs/vue-vben-admin/pull/3287 之后才把这个问题大体解决了(定位问题是在isEmpty的使用上面，而跟这个函数没有什么关系)。这时handleInputNumberValue这个函数不仅没发挥到应有的作用，并且导致了input系列组件输入输出类型不一致的问题 。例如输入number，string，其他的数据都会变成string
最近 https://github.com/vbenjs/vue-vben-admin/pull/3802 pr提过之后，目前的行为是 number变成number，然后其他的都变成string，但是仍然导致了 null 和 undefined等其他类型 会被设置成 string类型。

perf(util): remove handleInputNumberValue

---

src/components/Upload/src/components/ImageUpload.vue

发现imageUpload 的 disabled 不生效。下面是复现该问题的最小示例。设置了了disabled后这个表单项仍然可以进行点击
```vue
<template>
<Alert message="嵌入表单,加入resultFiled自定义返回值" />
<BasicForm @register="registerCustom" class="my-5" />
</template>
import { Alert } from 'ant-design-vue';
import { BasicForm, FormSchema, useForm } from '@/components/Form';
const schemasCustom: FormSchema[] = [
{
field: 'field4',
component: 'ImageUpload',
label: '字段4(ImageUpload)',
colProps: {
span: 8,
},
componentProps: {
disabled:true,
api: (file, progress) => {
return new Promise((resolve) => {
resolve({  
});
});
},
},
},
];
const [registerCustom] = …
```

fix(imgUpload): disabled not effect in the form

---

src/components/Form/src/BasicForm.vue
src/components/Form/src/hooks/useForm.ts
src/components/Form/src/hooks/useFormEvents.ts
src/components/Form/src/hooks/useFormValues.ts
src/components/Form/src/types/form.ts

fix https://github.com/vbenjs/vue-vben-admin/issues/3814 
resolve https://github.com/vbenjs/vue-vben-admin/issues/3795
这个pr主要做了三件事
- 解决reset在componentProps不能还原defaultValue 的bug
- 将 setdefaultvalue 和 setFieldsValue 进行分离。之前的setFieldsValue耦合了设置默认值和设置值的逻辑，现在的setFieldsValue只设置值，移除了设置默认值的逻辑
- 新增 resetDefaultField 方法，可以还原指定字段的 defaultValue
新功能测试 demo
```vue
<template>
<Alert message="测试新功能" />
<BasicForm @register="registerCustom" class="my-5" />
<Button  @click="reset">点我还原默认值</Button>
<Button  @click="set">点我设置默认值</Button>
</template>
import { Alert,Button } from 'ant-design-vue';
import { BasicForm, FormSchema, useForm } from '@/components/Form';
const schemasCustom: …
```

perf(BasicForm):fix invaild defaultValue && split-setdefault-setvalue && add resetDefaultField

---

src/components/Form/src/helper.ts
src/components/Form/src/hooks/useFormEvents.ts

fix https://github.com/vbenjs/vue-vben-admin/issues/3818

fix(BasicForm): setFieldsValue not work in form when use date comp

---

package.json
pnpm-lock.yaml
src/locales/lang/en/routes/demo.json
src/locales/lang/zh-CN/routes/demo.json
src/router/routes/modules/demo/feat.ts
src/views/demo/feat/screenshot/index.vue

feat: ScreenShot

---

src/components/Form/src/hooks/useAdvanced.ts

fix(BasicForm):FormSchema中使用ifShow隐藏字段时，默认表单查询重置按钮偏移计算未忽略ifShow=false隐藏的字段
问题复现：
1.使用ifShow隐藏某一字段，FormProps未配置actionColOptions
2.此段代码未忽略ifShow隐藏的字段
3.结果导致按钮未出现在行末
4.问题修正，忽略ifShow=false的字段

fix(BasicForm):修复FormSchema中使用ifShow隐藏字段时，默认表单查询重置按钮位置偏移量计算问题

---

src/components/Form/src/hooks/useForm.ts
src/components/Form/src/hooks/useFormEvents.ts
src/components/Form/src/hooks/useFormValues.ts

fix(BasicForm): when value is 0 or false resetFields is not work

---

src/components/Form/src/BasicForm.vue
src/components/Form/src/components/FormItem.vue
src/components/Form/src/types/form.ts

- 给 suffix 配对 ,添加prefix
以下是一个添加了prefix的最小示例
```vue
<template>
<Alert message="bug" />
<BasicForm @register="registerCustom" class="my-5" />
</template>
import { Alert } from 'ant-design-vue';
import { BasicForm, useForm } from '@/components/Form';
import { h } from 'vue';
import { InfoCircleOutlined } from '@ant-design/icons-vue';
import { Tooltip } from 'ant-design-vue';
const [registerCustom] = useForm({
baseColProps: { span: 24 },
labelWidth: 124,
schemas: [
{
field: 'field3',
label: 'label',
component: 'Input',
prefix: () => {
return h(Tooltip, { title: h('div', {}, 'ddd') }, [ …
```

feat(BasicForm): prefix

---

src/store/modules/multipleTab.ts

例如 tabA的fullpath为 /test?username=测试
关闭 tabB，本应该返回 tabA
但是由于 `replace` 会把 「测试」进行转义为「%E6%B5%8B%E8%AF%95」
因此最后会打开一个新的 tabC 为 /test?username=%E6%B5%8B%E8%AF%95
tabA 和 tabC 实际为同一个

fix: 路由参数存在非英文字符的情况下 会生成一个新的tab 而非返回原有tab

---

src/components/Application/src/search/useMenuSearch.ts

In commit 96ac362fa6a89af256cf8a84e4b667c195c6ea2e, I forgot to add the lowercase method for input keys. This omission caused a bug where the menu wouldn't display items if the search letter was capitalized.

fix: search menu now correctly lowercases input keys (resolved in r: 96ac362fa6a89af256cf8a84e4b667c195c6ea2e)

---

src/components/Table/src/hooks/useDataSource.ts

fix about this warnging:
[Vue warn] Computed is still dirty after getter evaluation, likely because a computed is mutating its own dependency in its getter. State mutations in computed getters should be avoided.
> Compute should not change own dependencies`s values!
> Keep original the type of getDataSourceRef

fix(useDataSource): state mutations in computed getters should be avoided

---

internal/vite-config/src/plugins/index.ts
package.json
pnpm-lock.yaml
vite.config.ts

feat: use devtools plugin instead of inspector plugin

---

src/components/Form/src/helper.ts

https://github.com/vbenjs/vue-vben-admin/blob/e69dd1e223a2e817805739f11823092992d14ae1/src/components/Form/src/helper.ts#L46-L48
TimePicker 判断重复

perf(form->util): duplicate judge

---

src/components/Form/src/hooks/useForm.ts

在使用 `useTable` 时，需要手动重置 `form` 表单，然后发送异步请求。
`useTable` 调用后解构出来的 `getForm` 调用 `resetFields` 未能即时同步页面变化到 `form` 表单内部的状态，就是说——页面发生变化后，`resetFields` 是异步重置表单的。
```vue
<template>
<BasicTable @register="registerTable">
<template #toolbar>
<a-button type="primary" @click="handleReset"> 重置表单 </a-button>
</template>
</BasicTable>
</template>
<script lang="ts" setup>
import { BasicTable, useTable } from '@/components/Table';
const options = { /* …
```

fix: 修复表单重置后，页面变化了，表单内部的状态未能及时同步

---

src/components/Form/src/BasicForm.vue
src/components/Form/src/components/FormItem.vue
src/components/Form/src/types/form.ts

添加 valueFormat方法 和 isHandleDefaultValue 属性(用来判断valueFormat是否对默认值生效)
例如下面例子，在upload组件的 field1中绑定的值只能是 string[] 格式的值。假如数据格式要求是要string格式的值，那么需要做额外的处理。现在可以通过 valueFormat这个方法，直接把field1 变成string格式的 
```vue
<template>
<Alert message="新功能测试" />
<BasicForm @register="registerValiate" class="my-5" />
</template>
import { Alert } from 'ant-design-vue';
import { BasicForm, FormSchema, useForm } from '@/components/Form';
import { useMessage } from '@/hooks/web/useMessage';
import { uploadApi } from '@/api/sys/upload';
const { createMessage } = useMessage();
const schemasValiate: FormSchema[] = [
{
field: …
```

feat(form): add valueFormat for schema

---

src/components/Upload/src/BasicUpload.vue
src/components/Upload/src/components/UploadModal.vue
src/components/Upload/src/components/UploadPreviewModal.vue
src/components/Upload/src/components/data.tsx
src/components/Upload/src/props.ts
src/components/Upload/src/types/typing.ts
src/views/demo/comp/upload/Upload4.vue

fix https://github.com/vbenjs/vue-vben-admin/issues/3867
fix https://github.com/vbenjs/vue-vben-admin/issues/3871
fix https://github.com/vbenjs/vue-vben-admin/issues/3850
使用者像之前一个传入 file 的 list 和 list[] 的时候不会受影响，在此基础上跟imgUpload一样添加了对单个值的处理(例如:"url")。绑定的form表单值也不会收到影响。
然后受到最大影响的是 暴露出来的 handleDelete 和 handleAdd，这两者传参进行了重构

chore(upload): use uid &&  fix handleDelete

---

internal/vite-config/src/config/application.ts
src/components/Table/src/hooks/useDataSource.ts

The same project code is built twice, but the build file names (hash value) obtained are different.
The code causing this problem is located in internal\vite-config\src\config\application.ts:
> entryFileNames: `assets/entry/[name]-[hash].js`
```ts
// ...
build: {
target: 'es2015',
cssTarget: 'chrome80',
rollupOptions: {
output: {
// 入口文件名（Here!）
entryFileNames: `assets/entry/[name]-[hash].js`,
manualChunks: {
vue: ['vue', 'pinia', 'vue-router'],
antd: ['ant-design-vue', '@ant-design/icons-vue'],
},
},
},
}
// ...
```
I think it should be reverted to:
```ts
// ...
build: {
target: 'es2015',
cssTarget: 'chrome80',
rollupOptions: {
output: {
// 入口文件名（Update here!）
entryFileNames: 'index.js',
manualChunks: {
vue: ['vue', 'pinia', 'vue-router'],
antd: ['ant-design-vue', …
```

chore(build): keep same hash for the same files

---

src/components/Table/src/hooks/useDataSource.ts

Issue: https://github.com/vbenjs/vue-vben-admin/issues/3887
Reference: https://github.com/vbenjs/vue-vben-admin/commit/fee808198e5c2038424a5f5b1da41b11d16d1508
Demo: https://vben.vvbin.cn/#/comp/table/basic

fix(useDataSource): BasicTable Component with dataSource is not working (hot fix)

---

src/components/Form/src/BasicForm.vue
src/components/Form/src/helper.ts
src/components/Form/src/hooks/useFormEvents.ts
src/components/Upload/src/BasicUpload.vue
src/components/Upload/src/components/ImageUpload.vue

fix https://github.com/vbenjs/vue-vben-admin/issues/3822
- 通过是否首次渲染来 分离upload/imageUpload 组件 的 change 和 update:value 。目的是解决首次渲染 upload系列组件的时候，直接调用change导致直接进行校验 从而不符合预期的问题
- upload/imageUpload 组件 的 defaultValue 和 setFieldValue 默认赋值 更改成默认是 array。目的是避免一开始输入是string，但是在数据的传递中变成array的不确定性问题

fix(upload): setValue and defaultValue uncertain && rule about first render

---

src/components/Table/src/components/settings/ColumnSetting.vue

```JavaScript
options.push({
label:
typeof col.title === "string"
? col.title
: col.customTitle === "string" //  typeof丢失
? col.customTitle
: "",
value:
typeof col.dataIndex === "string"
? col.dataIndex
: col.title === "string" //  typeof丢失
? col.title
: "",
column: {
defaultHidden: col.defaultHidden,
},
fixed: col.fixed,
});
```

修复 ColumnSettings.vue 中  columnOptions 在设置label和value时 typeof lost

---

src/store/modules/multipleTab.ts

在meta设置了realPath的情况下，`e.meta?.realPath ?? '' === realPath` 会返回 `e.meta.realPath`，需要加上 `()`
```this.tabList.filter((e) => e.meta?.realPath ?? '' === realPath).length >= dynamicLevel```
修改为：
```this.tabList.filter((e) => (e.meta?.realPath ?? '') === realPath).length >= dynamicLevel```

chore(multipleTab): Make the code more readable

---

build-local-docker-image.sh
deploy/nginx.conf
internal/lint-configs/commitlint-config/index.mjs
packages/effects/layouts/src/widgets/user-dropdown/user-dropdown.vue

fix: enablePreferences does not meet expectations

---

packages/effects/layouts/src/widgets/preferences/blocks/theme/theme.vue

chore: disable darkMenu when theme is 'dark'

---

src/store/modules/app.ts

The projectSettings default dark mode is not taking effect. In the getDarkMode function, setting.menuSetting.theme should be present and must be higher priority than darkMode.

fix: The projectSettings default dark mode is not taking effect in version 2

---

src/components/Form/src/hooks/useLabelWidth.ts

原来获取 label 宽度的代码使用了隐式类型转换，没有考虑到 `labelWidth` 为 `0` 的情况。
现在使用空值合并运算符 (??) 和 isDef 优化宽度判断逻辑，处理 `labelWidth` 可能为 `0` 的情况。

refactor(form): 使用空值合并运算符 (??) 和 isDef 优化宽度判断逻辑，处理 labelWidth 可能为 0 的情况

---

apps/web-ele/src/views/demos/element/index.vue
internal/tailwind-config/src/index.ts
packages/@core/base/design/src/design-tokens/dark/index.css
packages/@core/base/design/src/design-tokens/default/index.css
packages/effects/hooks/src/use-design-tokens.ts

修复ElementPlus组件库的表格斑马纹样式在暗黑模式下的问题

fix: stripe table style for element plus, fixed: #4501

---

docs/src/en/guide/essentials/settings.md
docs/src/guide/essentials/settings.md
packages/@core/preferences/__tests__/__snapshots__/config.test.ts.snap
packages/@core/preferences/src/config.ts
packages/@core/preferences/src/types.ts
packages/@core/ui-kit/tabs-ui/src/components/tabs-chrome/tabs.vue
packages/@core/ui-kit/tabs-ui/src/components/tabs/tabs.vue
packages/@core/ui-kit/tabs-ui/src/tabs-view.vue
packages/@core/ui-kit/tabs-ui/src/types.ts
packages/@core/ui-kit/tabs-ui/src/use-tabs-drag.ts
packages/effects/layouts/src/basic/tabbar/tabbar.vue
packages/effects/layouts/src/widgets/preferences/blocks/layout/tabbar.vue
packages/effects/layouts/src/widgets/preferences/preferences-drawer.vue
packages/locales/src/langs/en-US.json
packages/locales/src/langs/zh-CN.json

单词拼写纠正： `dragable`  → `draggable`

chore: correct spelling for 'dragable'

---

packages/@core/base/shared/package.json
packages/effects/common-ui/src/ui/authentication/code-login.vue
packages/effects/common-ui/src/ui/authentication/forget-password.vue
packages/effects/common-ui/src/ui/authentication/login.vue
packages/effects/common-ui/src/ui/authentication/register.vue
packages/effects/plugins/src/vxe-table/use-vxe-grid.vue
pnpm-lock.yaml
pnpm-workspace.yaml

perf: expose the formApi for a login form

---

docs/src/components/common-ui/vben-vxe-table.md
docs/src/en/guide/essentials/styles.md
docs/src/guide/essentials/styles.md
internal/vite-config/src/config/application.ts
packages/@core/ui-kit/form-ui/src/form-api.ts
packages/effects/plugins/src/vxe-table/use-vxe-grid.vue
packages/styles/src/global/index.scss
pnpm-lock.yaml
pnpm-workspace.yaml

close #4824
fixed  #4785 
fixed #4752

fix: when the form is destroyed, the form parameters still exist

---

packages/effects/plugins/src/vxe-table/use-vxe-grid.vue

修复grid的toolbarConfig.tools配置在某些场景下可能不起作用的问题

fix: grid tools in toolbar config not working as expected

---

packages/styles/src/ele/index.css

Element Plus的loading组件默认zIndex太高，会遮挡基础布局中的下拉菜单之类的组件

style: element plus loading style fixed

---

docs/src/components/common-ui/vben-api-component.md
docs/src/components/common-ui/vben-modal.md

docs: update docs

---

packages/utils/src/helpers/get-popup-container.ts

修复getPopupContainer的逻辑，优先返回最近的一个form祖先。解决因为formItem的overflow-hidden导致弹出层被截断的问题
fix #5610

fix: getPopupContainer will return closet form first

---

packages/@core/ui-kit/popup-ui/src/drawer/__tests__/drawer-api.test.ts
packages/@core/ui-kit/popup-ui/src/drawer/drawer-api.ts
packages/@core/ui-kit/popup-ui/src/drawer/drawer.ts

drawer的beforeClose与modal保持一致  支持Promise

perf: `beforeClose` of drawer support promise

---

packages/effects/plugins/src/vxe-table/style.css

perf: vxe-table 活动颜色，松开颜色，按下颜色，没有随主题颜色修复

---

packages/utils/src/helpers/generate-menus.ts

When children is undefined, use empty array as fallback to prevent potential runtime errors. This matches the behavior when hideChildrenInMenu is true.

fix: handle undefined children in generate-menus

---

packages/effects/plugins/src/vxe-table/index.ts

style: fix lint error

---

packages/effects/common-ui/src/components/api-component/api-component.vue

* 目前在fetchApi中参数使用的是props的params, 但是当innerParams变化时，api调用使用的props的params并不包含innerParams。所以应该改成使用计算属性的params 
* beforeFetch回调使用params的副本
* 修复在上一个请求尚未完成前如果params发生了变更，将不会再触发新的api请求。这是一种较极端的情况

fix: 修复 API 组件中的 fetchApi 函数的参数使用问题
